module.exports = { 
    peerMentorChecklist:{ 
        entered_wrong_phone_format:[
            ['firstname','middlename','lastname','+255775456789','shehia']
        ],
        less_than_two_characters:[
            ['f','m','l','0775456789','s']
        ],
        fill_form_with_yes_response:[
            ['firstname','middlename','lastname','0775456789','shehia'],['yes','yes','yes','yes','yes','yes'], 
            ['yes','yes','yes'],['yes','yes','yes','yes'],
            ['none']
        ], 
        fill_form_with_average_response:[
            ['firstname','middlename','lastname','0775456789','shehia'],['average','average','average','average','average','average'], 
            ['average','average','average'],['average','average','average','average'],
            ['none']
        ],
        fill_form_with_no_response:[
            ['firstname','middlename','lastname','0775456789','shehia'],
            ['no','reason',
             'no','reason',
             'no','reason',
             'no','reason',
             'no','reason',
             'no','reason',], 
            ['no','reason',
             'no','reason',
             'no','reason',],
            ['no','reason',
             'no','reason',
             'no','reason',
             'no','reason'],
            [['tech_team','chmt','supervisor'],
             ['tech_comments'],
             ['chmt_comments'],
             ['supervisor_comments']] 
        ],
        select_all_multiselect_options:[
            ['firstname','middlename','lastname','0775456789','shehia'],
            ['no','reason',
             'no','reason',
             'no','reason',
             'no','reason',
             'no','reason',
             'no','reason',], 
            ['no','reason',
             'no','reason',
             'no','reason',],
            ['no','reason',
             'no','reason',
             'no','reason',
             'no','reason'],
            [['tech_team','chmt','supervisor','none']] 
        ],
        fill_empty_form:[]
    }
};