const shehiaNames = [
    'Mbuyuni',
    'Dodo',
    'Kisiwa Panza',
    'Kuukuu',
    'Kendwa',
    'Mtangani',
    'Chokocho',
    'Kiwani',
    'Shamiani',
    'Kangani',
    'Changaweni',
    'Mgagadu',
    'Chambani',
    'Jombwe',
    'Mjimbini',
    'Makoongwe',
    'Ng\'ombeni',
    'Mchakwe',
    'Msingini',
    'Wawi',
    'Mgelema',
    'Shungi',
    'Vitongoji',
    'Mvumoni',
    'Pujini',
    'Mgogoni',
    'Ndagoni',
    'Chanjaani',
    'Kichungwani',
    'Michungwani',
    'Mfikiwa',
    'Tibirinzi',
    'Wara',
    'Gombani',
    'Matale',
    'Mjini Ole',
    'Shanake',
    'Sizini',
    'Shumba Mjini',
    'Mjini Wingwi',
    'Maziwa Ng\'ombe',
    'Msuka Magharibi',
    'Wingwi Mapofu',
    'Chimba',
    'Kifundi',
    'Msuka Mashariki',
    'Shumba Viamboni', 
    'Kipange',
    'Chamboni',
    'Mihogoni',
    'Mtemani',
    'Tumbe Mashariki',
    'Tumbe Magharibi',
    'Micheweni',
    'Chwale',
    'Finya',
    'Piki',
    'Mjananza',   
    'Fundo',
    'Limbani',
    'Mzambarau Takao',
    'Kangagani',
    'Mtambwe Kusini',
    'Kiungoni',
    'Ukunjwi',
    'Mtemani',
    'Mgogoni',
    'Pembeni',
    'Kojani',
    'Kipangani',
    'Bopwe',
    'Mlindo',
    'Uvivini',
    'Potoa',
    'Pwani Mchangani',
    'Kilindi',
    'Kibeni',
    'Nungwi Kiungani',
    'Kidombo',
    'Mkokotoni',
    'Pitanazako',
    'Chutama',
    'Mbuyutende',
    'Matemwe Kusini',
    'Mcheza Shauri',
    'Kivunge',
    'Gamba',
    'Mto Wapwani',
    'Kinyasini',
    'Mtakuja',
    'Juga kuu',
    'Matetema',
    'Mgambo',
    'Kiombamvua',
    'Donge Pwani',
    'Mnyimbi',
    'Mkadini',
    'Zingwezingwe',
    'Kisongoni',
    'Donge Vijibweni',
    'Majenzi',
    'Kilombero',
    'Kiongwe Kidogo',
    'Mkataleni',
    'Kwagube',
    'Njiayamtoni',
    'Donge Mbiji',
    'Mbaleni',
    'Misufini',
    'Kidazini'
  ];
   
  function shouldShowASRHForm(shehiaName = null) { return shehiaNames.includes(shehiaName); }
  
  module.exports={
    shouldShowASRHForm:shouldShowASRHForm};