const shehiaNames = [
	'Mbuyuni',
	'Dodo',
	'Kisiwa Panza',
	'Kuukuu',
	'Kendwa',
	'Mtangani',
	'Chokocho',
	'Kiwani',
	'Shamiani',
	'Kangani',
	'Changaweni',
	'Mgagadu',
	'Chambani',
	'Jombwe',
	'Mjimbini',
	'Makoongwe',
	'Ng\'ombeni',
	'Mchakwe',
	'Msingini',
	'Wawi',
	'Mgelema',
	'Shungi',
	'Vitongoji',
	'Mvumoni',
	'Pujini',
	'Mgogoni',
	'Ndagoni',
	'Chanjaani',
	'Kichungwani',
	'Michungwani',
	'Mfikiwa',
	'Tibirinzi',
	'Wara',
	'Gombani',
	'Matale',
	'Mjini Ole',
	'Shanake',
	'Sizini',
	'Shumba Mjini',
	'Mjini Wingwi',
	'Maziwa Ng\'ombe',
	'Msuka Magharibi',
	'Wingwi Mapofu',
	'Chimba',
	'Kifundi',
	'Msuka Mashariki',
	'Shumba Viamboni', 
	'Kipange',
	'Chamboni',
	'Mihogoni',
	'Mtemani',
	'Tumbe Mashariki',
	'Tumbe Magharibi',
	'Micheweni',
	'Chwale',
	'Finya',
	'Piki',
	'Mjananza',   
	'Fundo',
	'Limbani',
	'Mzambarau Takao',
	'Kangagani',
	'Mtambwe Kusini',
	'Kiungoni',
	'Ukunjwi',
	'Mtemani',
	'Mgogoni',
	'Pembeni',
	'Kojani',
	'Kipangani',
	'Bopwe',
	'Mlindo',
	'Uvivini',
	'Potoa',
	'Pwani Mchangani',
	'Kilindi',
	'Kibeni',
	'Nungwi Kiungani',
	'Kidombo',
	'Mkokotoni',
	'Pitanazako',
	'Chutama',
	'Mbuyutende',
	'Matemwe Kusini',
	'Mcheza Shauri',
	'Kivunge',
	'Gamba',
	'Mto Wapwani',
	'Kinyasini',
	'Mtakuja',
	'Juga kuu',
	'Matetema',
	'Mgambo',
	'Kiombamvua',
	'Donge Pwani',
	'Mnyimbi',
	'Mkadini',
	'Zingwezingwe',
	'Kisongoni',
	'Donge Vijibweni',
	'Majenzi',
	'Kilombero',
	'Kiongwe Kidogo',
	'Mkataleni',
	'Kwagube',
	'Njiayamtoni',
	'Donge Mbiji',
	'Mbaleni',
	'Dongwe',
	'Misufini',
	'Kidazini',
	//Urban
	'Muungano',
	'Kilimahewa bondeni',
	'Matarumbeta',
	'Kilimahewajuu',
	'Mwembe makumbi',
	'Magomeni',
	'Malindi',
	'Shaurimoyo',
	'Makadara',
	'Migombani',
	'Urusi',
	'Nyerere',
	'Kwahani',
	'Mikunguni',
	'Kwaalinatu',
	'Banko',
	'Mkele',
	'Miembeni',
	'Kikwajunijuu',
	'Kwaalimsha',
	//West A 
	'Bububu ',
	'Kizimbani',
	'Mchikichini',
	'Mtoni Chemchem',
	'Sharifu msa',
	'Munduli',
	'Kikaangoni',
	'Mwakaje',
	'Muwembemchomeke',
	'Mfenesini',
	'Masingini',
	'Kizimbani',
	'Kibweni',
	'Mtopepo',
	'Hawaii',
	'kijichi',
	'Kwagoa',
	'Mwanyanya',
	//WestB
	'Kibondeni',
	'Fuoni migombani',
	'Kisima majongoo',
	'Tomondo',
	'Pangawe',
	'Mwanakwerekwe',
	'Fuoni kipungani',
	'Uzi',
	'Mombasa',
	'Shakani',
	'Dimani',
	'Bweleo',
	'Taveta',
	'Michungwani',
	'Mnarani',
	'Magogoni',
	'Binguni',
//Central and South
	'Bungi',
	'Dongwe',
	'Jambiani Kikadini',
	'Kibuteni',
	'Kijibwemtu',
	'Kijini',
	'Kitogani',
	'Kizimkazi Dimbani',
	'Machui',
	'Mchangani Shamba',
	'Mgeni Haji',
	'Michamvi',
	'Mtende',
	'Muyuni A',
	'Ndijan Mwembepunda',
	'Pagali',
	'Pete',
	'Pongwe',
	'Tasani',
	'Tunduni',
	'Tunguu',
	'Ukongoroni',
	'Umbuji',
	'Unguja Ukuu Kaebona',
	'Uroa',
	'Uzini'
  ];
   
  function shouldShowASRHForm(shehiaName = null) { return shehiaNames.includes(shehiaName); }
  
  module.exports={
    shouldShowASRHForm:shouldShowASRHForm};
