------------------------------------------------------------
-- Materialized view to show table of chv status.
------------------------------------------------------------
DROP MATERIALIZED VIEW IF EXISTS chv_status;
CREATE MATERIALIZED VIEW chv_status AS
(
  WITH chv_payment_groups AS (
    SELECT * FROM
      (VALUES
        ('Aisha Abdallah Hamadi','Chumbuni',1),
        ('Aisha Makame Jaku','Chumbuni',1),
        ('Asha Juma Abdallah','Banko',1),
        ('Asha Mtumwa Soraka','Banko',1),
        ('Asha Othman Salum','Jangombe',1),
        ('Aziza Hassan Khamis','Jangombe',1),
        ('Bikombo Khamis Foum','Banko',1),
        ('Farhiya Ali Omar','Banko',1),
        ('Fatuma Juma Makame','Chumbuni',1),
        ('Haji Ismail Ussi','Chumbuni',1),
        ('Halima Amour Haji','Chumbuni',1),
        ('Hemed Ramadhan Hemed','Amani',1),
        ('Jamila Khamis Hamada','Jangombe',1),
        ('Khadija Alawi Jumbe','Banko',1),
        ('Khuzeima Khamis Juma','Chumbuni',1),
        ('Lailat Hassan Khamis','Jangombe',1),
        ('Lubayna Nassor Hamad','Amani',1),
        ('Makame Sheha Ali','Banko',1),
        ('Miza Haji Mwalimu','Jangombe',1),
        ('Mkemimi Silima Khamis','Amani',1),
        ('Mtumwa Salum Haji','Amani',1),
        ('Mtumwa Salum Juma','Chumbuni',1),
        ('Mtumwa Soud Said','Amani',1),
        ('Mwajabu Mrindoko Mbwambo','Jangombe',1),
        ('Mwaka Faki Iddi','Banko',1),
        ('Mwanahamis Abdallah Bakari','Jangombe',1),
        ('Mwanjia Salum Shame','Chumbuni',1),
        ('Mwatima Suleiman Khamis','Jangombe',1),
        ('Nasra Nyage Vuai','Chumbuni',1),
        ('Nuru Khamis Haji','Banko',1),
        ('Nusura Kassim Bakar','Amani',1),
        ('Rabiya Ramadhan Khalfan','Amani',1),
        ('Rukia Maulid Jecha','Jangombe',1),
        ('Salama Simai Khamis','Chumbuni',1),
        ('Salma Mohamed Said','Amani',1),
        ('Salum Saad Abdulla','Amani',1),
        ('Shadida Mussa Salum','Banko',1),
        ('Sihuyu Issa Sadalla','Jangombe',1),
        ('Tatu Juma Ali','Jangombe',1),
        ('Time Khatib Ramadhan','Amani',1),
        ('Zainab Khamis Jaffar','Banko',1),
        ('Abubakar Ali Mrisho','K/mtipura',1),
        ('Aisha Walid Kitwana','K/mtipura',1),
        ('Amina Juma Mustafa','K/mtipura',1),
        ('Amina Nassor Ali','K/mtipura',1),
        ('Biata Joseph Selestean','K/chekundu',1),
        ('Fatma Abdalla Juma','K/hewa bondeni',1),
        ('Fatma Sadun Amiri','K/hewa bondeni',1),
        ('Fatma Suleiman Ame','K/mtipura',1),
        ('Fumu Haji Foum','K/hewa juu',1),
        ('Hanifa Salum Juma','K/chekundu',1),
        ('Juwairia Suleiman Mkombe','K/mtipura',1),
        ('Khadija Omar Kheir','K/hewa juu',1),
        ('Kidawa Juma Mussa','Gulioni',1),
        ('Made Gharib Kombo','K/mtipura',1),
        ('Maryam Adam Ali','K/hewa juu',1),
        ('Maryam Choum Juma','K/mtipura',1),
        ('Miza Simai Khamis','K/hewa juu',1),
        ('Mtenje Jirani Mtenje','K/hewa bondeni',1),
        ('Munawar Almas Khamis','K/hewa bondeni',1),
        ('Muniral Foum Juma','Gulioni',1),
        ('Muzdafat Ali Denge','K/hewa juu',1),
        ('Mwahija Khamis Said','K/chekundu',1),
        ('Mwanaali Ramadhan Haji','K/mtipura',1),
        ('Mwanamvua Khamis Fikirini','K/hewa juu',1),
        ('Nadia Ali Hassan','K/mtipura',1),
        ('Nasra Miraji Ali','K/hewa bondeni',1),
        ('Njuma Juma Ali','Gulioni',1),
        ('Omar Mussa Omar','K/hewa juu',1),
        ('Patima Makame Madaha','K/hewa bondeni',1),
        ('Rahma Abdalla Ali','K/hewa bondeni',1),
        ('Rahma Kombo Choum','K/hewa bondeni',1),
        ('Rahma Mohamed Ali','K/hewa juu',1),
        ('Raya Mohammed Khalfan','K/hewa juu',1),
        ('Rukia Talib Mohamed','K/mtipura',1),
        ('Sabrina Mlekwa Ali','K/hewa bondeni',1),
        ('Salama Talib Mohammed','K/mtipura',1),
        ('Shadya Abdalla Abdillah','K/chekundu',1),
        ('Sinna Mohammed Khamis','K/mtipura',1),
        ('Sisawa Khamis Ame','K/hewa juu',1),
        ('Tatu Suleiman Ame','K/mtipura',1),
        ('Tumu Mzee Ali','Gulioni',1),
        ('Zariha Miraji Ali','K/hewa bondeni',1),
        ('Agnes George Sunna','Kiponda',1),
        ('Ally Othman Khamis','Kiponda',1),
        ('Amina Rashid Abasi','Kiponda',1),
        ('Asha Bilali Juma','Karakana',1),
        ('Asha Kondo Bakar','Kisiwandui',1),
        ('Asya Rashid Bakar','M/shauri',1),
        ('Biubwa Juma Khamis','Karakana',1),
        ('Fadhila Abdallah Ali','M/shauri',1),
        ('Fatihiya Abdul Hakim','Kisima majongoo',1),
        ('Fatma Haji Ali','Karakana',1),
        ('Fatuma Khamis Ame','Kikwajuni juu',1),
        ('Habiba Khamis Makamae','Karakana',1),
        ('Hadia Abdallah Makame','Kisima majongoo',1),
        ('Hashim Ali Ahmada','Kikwajuni juu',1),
        ('Hasina Mosi Jabu','Kilimani',1),
        ('Huzaima Hassan Mrisho','Karakana',1),
        ('Ibrahim Haji Aley','M/shauri',1),
        ('Jaidi Khamis Said','Kilimani',1),
        ('Khadija Juma Ramadhan','Kwaalamsha',1),
        ('Khadija Khatib Hamad','Kikwajuni bondeni',1),
        ('Laila Ali Hamad','Kilimani',1),
        ('Mgeni Abdalla Seif','Kwaalamsha',1),
        ('Mussa Khamis Khamis','Kwaalamsha',1),
        ('Mwanaisha Kombo Abdalla','Karakana',1),
        ('Nageeb Ahmed Abdul Karim','Kikwajuni bondeni',1),
        ('Nasma Saidi Ali','Kisima majongoo',1),
        ('Nasra Machano Khamis','Karakana',1),
        ('Pili Ramadhan Fadhil','Kikwajuni juu',1),
        ('Rayan Khamis Omar','Kilimani',1),
        ('Riziki Juma Hassan','Kisima majongoo',1),
        ('Rukia Abdallah Daud','Kwaalamsha',1),
        ('Sabiha Mahmoud Abdallah','Karakana',1),
        ('Sakina Mrisho Swedi','Kilimani',1),
        ('Salama Ali Mohammed','Kisima majongoo',1),
        ('Salhia Said Mohamed','Kisiwandui',1),
        ('Salma Juma Mtumwa','Kwaalamsha',1),
        ('Salwa Salum Ali','Kikwajuni juu',1),
        ('Sihaba Mustafa Haji','Kikwajuni bondeni',1),
        ('Stara Juma Makame','Kikwajuni bondeni',1),
        ('Tatu Juma Kidawa','Karakana',1),
        ('Zahra Seif Issa','Kwaalamsha',1),
        ('Zena Mussa Khairalla','Kisiwandui',1),
        ('Ali Rashid Saleh','Kwabinti hamrani',1),
        ('Ameir Khamis Hassan','Kwaalinatoo',1),
        ('Asia Ali Hassan','Kwabinti hamrani',1),
        ('Bimkubwa Abdi Mohamed','Kwa wazee',1),
        ('Fathiya Khamis Hussein','Kwa wazee',1),
        ('Fatma Yussuf Omar','Kwa wazee',1),
        ('Feda Mohamed Juma','Kwabinti hamrani',1),
        ('Hafsa Juma Ali','Kwaalinatoo',1),
        ('Halima Mohd Said','Kwaalinatoo',1),
        ('Husna Ubwa Ali','M/ladu',1),
        ('Juma Khamis Juma','Kwaalinatoo',1),
        ('Khadija Hasan Haji','Kwa wazee',1),
        ('Khadija Juma Bai','Kwabinti hamrani',1),
        ('Khamis Kombo Khamis','Kwaalinatoo',1),
        ('Maryam Hassan Sungura','Kwabinti hamrani',1),
        ('Maryam Salum Rashid','Kwa wazee',1),
        ('Maua Mbarouk Ramadhani','Kwabinti hamrani',1),
        ('Mbarouk Is-Hak Haji','Kwaalinatoo',1),
        ('Meya Salum Rashid','Kwa wazee',1),
        ('Moh''D Omar Moh''D','Kwa wazee',1),
        ('Mohammed Juma Ali','Kwabinti hamrani',1),
        ('Moza Ismail Haji','Kwabinti hamrani',1),
        ('Mufida Idarous Mohd','Kwaalinatoo',1),
        ('Muhsin Abdulrahman Yussuf','Kwaalinatoo',1),
        ('Mwanahija Hassan Iddi','Kwabinti hamrani',1),
        ('Mwanakhamis Ameir Kassim','Kwabinti hamrani',1),
        ('Mwanakombo Hussein Beka','Kwa wazee',1),
        ('Nadra Abdulla Ramadhan','Kwabinti hamrani',1),
        ('Raya Faraji Faiz','Kwa wazee',1),
        ('Rehema Khamis Rajab','Kwaalinatoo',1),
        ('Rosemarry Faustin Banz','Kwabinti hamrani',1),
        ('Saada Suwed Abdallah','M/ladu',1),
        ('Salma Juma Ali','M/ladu',1),
        ('Salma Mohamed Msham','Kwabinti hamrani',1),
        ('Salma Mussa Yussuf','Kwa wazee',1),
        ('Subira Khamis Madari','Kwa wazee',1),
        ('Tatu Abdulrahman Mwinyi','Kwabinti hamrani',1),
        ('Tatu Kombo Kheir','Kwa wazee',1),
        ('Warda Shaib Hassan','Kwabinti hamrani',1),
        ('Zuleifa Khamis Hassan','Kwa wazee',1),
        ('Zulfa Ramadhan Jecha','Kwaalinatoo',1),
        ('Ally Makame Kombo','M/makumbi',1),
        ('Arafa Hassan Haji','Kwahani',1),
        ('Asha Ismail Rajab','Kwahani',1),
        ('Fatma Ali Khamis','Magomeni',1),
        ('Fatma Haji Sheha','Magomeni',1),
        ('Fatma Mossi Mati','M/tanga',1),
        ('Habibu Khamis Khatib','Kwamtumwa jeni',1),
        ('Hadia Bakili Silima','Kwahani',1),
        ('Hasnath Mashaka Kavula','Kwamtumwa jeni',1),
        ('Ilham Ibrahim Ali','M/tanga',1),
        ('Khadija Makame Khamis','Magomeni',1),
        ('Khadija Mgasho Mussa','Kwamtumwa jeni',1),
        ('Kidawa Shaaban Ramadhan','Kwahani',1),
        ('Kulthum Omar Juma','M/makumbi',1),
        ('Maryam Mzee Mataka','Kwamtumwa jeni',1),
        ('Maryam Saleh Juma','Kwahani',1),
        ('Maryam Saleh Mohamed','M/makumbi',1),
        ('Mtumwa Simai Dau','M/makumbi',1),
        ('Mwajuma Abbas Rashida','Magomeni',1),
        ('Mwajuma Khatib Omar','M/makumbi',1),
        ('Mwanakhamis Saleh Juma','Kwahani',1),
        ('Mwashabani Rajab Ali','Kwamtumwa jeni',1),
        ('Naila Ali Hassan','Magomeni',1),
        ('Nali Saidi Muombwa','Kwamtumwa jeni',1),
        ('Nasra Abdalla Juma','Magomeni',1),
        ('Nassra Issa Kassim','Kwamtumwa jeni',1),
        ('Rehema Abdalla Suleiman','Kwahani',1),
        ('Rukaiya Juma Othman','Kwahani',1),
        ('Sabiamu Hamuli Maokola','Magomeni',1),
        ('Safia Abdallah Khamis','M/tanga',1),
        ('Safia Makame Ali','Magomeni',1),
        ('Salha Mohamed Faki','Kwamtumwa jeni',1),
        ('Suhaila Rashid Nassor','M/tanga',1),
        ('Suleiman Machano Tano','M/makumbi',1),
        ('Sumaiyya Juma Ahmada','M/tanga',1),
        ('Tatu Ali Omar','M/makumbi',1),
        ('Tatu Othman Kipingo','Magomeni',1),
        ('Thuwayba Khamis Hilal','Magomeni',1),
        ('Zawad Khamis Juma','Kwahani',1),
        ('Zinduna Khatib Ali','Kwamtumwa jeni',1),
        ('Zulfa Ali Khamis','Magomeni',1),
        ('Abdilah Said Msabah','Malindi',2),
        ('Abdulghafur Hassan Masoud','Malindi',2),
        ('Ahmed Ali Makame','Shangani',2),
        ('Ali Mzee Mshenga','Masumbani',2),
        ('Amina Kassim Yussuf','Mapinduzi',2),
        ('Arafa Khamis Makame','Masumbani',2),
        ('Asha Juma Abdallah','Malindi',2),
        ('Ashura Salum Badru','Shangani',2),
        ('Asma Darwesh Ishaq','Maruhubi',2),
        ('Faida Mbaraka Mohamed','Masumbani',2),
        ('Haitham Ally Suleiman','Makadara',2),
        ('Haji Makame Haji','Mapinduzi',2),
        ('Halima Ali Hamad','Maruhubi',2),
        ('Hussein Tumba Said','Malindi',2),
        ('Jannatbhai Suleiman Jussa','Malindi',2),
        ('Kazija Ali Haji','Masumbani',2),
        ('Kazija Kazimoto Hussein','Masumbani',2),
        ('Kazija Khamis Mussa','Makadara',2),
        ('Khadija Kongo Yussuf','Mapinduzi',2),
        ('Khairat Mohammed Salum','Shangani',2),
        ('Lut-Fiya Maulid Ismail','Makadara',2),
        ('Lutfia Ali Mohamed','Makadara',2),
        ('Machano Shauri Haji','Maruhubi',2),
        ('Maimuna Sharif Juma','Masumbani',2),
        ('Moza Haroub Ishaq','Mapinduzi',2),
        ('Munira Ali Makame','Shangani',2),
        ('Mwajuma Sharifu Juma','Maruhubi',2),
        ('Ngwali Abdurazaq Ngwali','Maruhubi',2),
        ('Rahma Rashid Khamis','Shangani',2),
        ('Rauhiya Haji Sharia','Masumbani',2),
        ('Rukia Idarous Nassor','Shangani',2),
        ('Sabrina Pandu Khamis','Maruhubi',2),
        ('Safiya Ali Himid','Mapinduzi',2),
        ('Saidi Salim Choum','Masumbani',2),
        ('Siwajibu Zamiri Ameir','Masumbani',2),
        ('Suleiman Makame Mshenga','Makadara',2),
        ('Wanje Kombo Bakari','Maruhubi',2),
        ('Warda Abdallah Suleiman','Makadara',2),
        ('Zaina Khatib Mwinyi','Shangani',2),
        ('Zuberi Hemed Ali','Mapinduzi',2),
        ('Ali Ramadhan Juma','Migombani',2),
        ('Amina Bakari Mussa','Migombani',2),
        ('Amina Salum Seif','Vikokotoni',2),
        ('Asha Amour Mussa','Miembeni',2),
        ('Asha Hassan Omar','Mboriborini',2),
        ('Asya Abdallah Mussa','Mboriborini',2),
        ('Asya Hassan Ali','Mikunguni',2),
        ('Dalila Thabit Mohammed','Mikunguni',2),
        ('Fahma Rajab Mohamed','Migombani',2),
        ('Farhat Soud Rajab','Matarumbeta',2),
        ('Fatma Ali Juma','Mboriborini',2),
        ('Fatma Benard Saanani','Migombani',2),
        ('Fatma Mohamed Salum','Migombani',2),
        ('Fatma Mohammed Mshenga','Matarumbeta',2),
        ('Fatma Omar Ali','Matarumbeta',2),
        ('Hadia Abdalla Ame','Mboriborini',2),
        ('Husna Mikidadi Mateo','Mboriborini',2),
        ('Kauthar Hassan Othman','Miembeni',2),
        ('Khadija Abdi Waziri','Migombani',2),
        ('Khadija Badru Shaib','Matarumbeta',2),
        ('Khamis Ali Khamis','Vikokotoni',2),
        ('Kulthum Abdalla Madina','Migombani',2),
        ('Maida Mzee Haji','Mboriborini',2),
        ('Moza Muslih Juma','Migombani',2),
        ('Mtumwa Haji Said','Vikokotoni',2),
        ('Mwajuma Mzee Msuri','Mikunguni',2),
        ('Mwanaidi Shaaban Ibrahim','Miembeni',2),
        ('Mwatum Suleiman Mohamed','Miembeni',2),
        ('Rahima Mzee Juma','Miembeni',2),
        ('Rahma Abbas Ramadhan','Mikunguni',2),
        ('Rahma Omar Khamis','Migombani',2),
        ('Sabra Juma Haji','Mikunguni',2),
        ('Salama Simba Abdallah','Matarumbeta',2),
        ('Salha Khamis Shaha','Migombani',2),
        ('Shaha Bakari Said','Migombani',2),
        ('Shorani Ali Mohamed','Migombani',2),
        ('Suleiman Ali Said','Migombani',2),
        ('Warda Songoro Sadiki','Mboriborini',2),
        ('Zeina Hamad Mussa','Migombani',2),
        ('Zuwena Haji Khamis','Mboriborini',2),
        ('Abdulkarim Khamis Matulubu','Muungano',2),
        ('Abdulwahid Salum Mohamed','Mkunazini',2),
        ('Abrahman Suleiman Juma','Mitiulaya',2),
        ('Abrazak Ali Silima','Mkele',2),
        ('Aisha Mohammed Abdullah','Muungano',2),
        ('Asha Iddi Mohammed','Mitiulaya',2),
        ('Azza Abdillah Mohammed','Mitiulaya',2),
        ('Bikombo Mohammed Khamis','Nyerere',2),
        ('Faida Sadifa Haji','Mkele',2),
        ('Hafsa Abrahman Mohammed','Muungano',2),
        ('Hudhaima Abubakar Salmini','Muungano',2),
        ('Idrissa Yussuf Khamis','Nyerere',2),
        ('Issa Omar Msisiri','Mnazi mmoja',2),
        ('Juma Khamis Ali','Muungano',2),
        ('Khadija Mbarouk Iddi','R/leo',2),
        ('Khadija Said Abdalla','Nyerere',2),
        ('Khalfan Khatibu Ibrahim','Nyerere',2),
        ('Khamis Haji Golo','Mitiulaya',2),
        ('Maryam Khamis Ali','Muungano',2),
        ('Maryam Mrisho Vuai','Mitiulaya',2),
        ('Miza Ali Chande','Nyerere',2),
        ('Mtumwa Ali Juma','Muungano',2),
        ('Mwajuma Omar Rubea','Nyerere',2),
        ('Mwajuma Rajab Saleh','Nyerere',2),
        ('Mwanabaraka Khamis Shehe','R/leo',2),
        ('Mwanaid Khamis Khamis','Mkele',2),
        ('Mwanajuma Ramadhan Ali','Muungano',2),
        ('Mwatum Abdi Malik','Mkele',2),
        ('Nuru Mohamed Ali','R/leo',2),
        ('Omar Hassan Khamis','Mitiulaya',2),
        ('Rahma Nassor Moh''D','Mnazi mmoja',2),
        ('Rashid Dadi Akida','Mkele',2),
        ('Riziki Nassor Hassan','Nyerere',2),
        ('Safirina Abdallah Said','Nyerere',2),
        ('Said Juma Khamis','Mkunazini',2),
        ('Said Shibu Hassan','Mitiulaya',2),
        ('Salha Said Suleiman','Mnazi mmoja',2),
        ('Sayda Juma Saadat','Mkunazini',2),
        ('Tatu Juma Iddi','Mkele',2),
        ('Zuhura Ali Vuai','Muungano',2),
        ('Amina Abdalla Ameir','Mpendae',2),
        ('Asha Haji Mussa','Muembe madema',2),
        ('Asha Juma Ali','Sebleni',2),
        ('Asia Slaiman Salum','Mpendae',2),
        ('Bizume Faki Khamis','Sebleni',2),
        ('Chagueni Mwalimu Juma','Sebleni',2),
        ('Fahad Juma Mustafa','Muembe madema',2),
        ('Fatma Ame Maisha','Sogea',2),
        ('Fatma Haji Mussa','Sebleni',2),
        ('Fatma Mohamed Maulid','Sebleni',2),
        ('Fauzia Ali Mussa','Sogea',2),
        ('Hamisa Ali Hamdu','Mpendae',2),
        ('Hassan Rakwe Iddi','Mpendae',2),
        ('Hawa Omar Juma','Saateni',2),
        ('Hidaya Abdulla Muhammed','Mpendae',2),
        ('Husaina Mshenga Khamis','Saateni',2),
        ('Ibrahim Makame Faki','Sebleni',2),
        ('Juma Issa Juma','Sogea',2),
        ('Kauthar Abdullah Othman','Sogea',2),
        ('Khamis Abas Sheha','Sebleni',2),
        ('Khamis Hassan Mohammed','Muembe madema',2),
        ('Khayrat Abdulhamid Hamdu','Saateni',2),
        ('Kibibi Suleiman Ameir','Sogea',2),
        ('Meiye Said Ali','Mpendae',2),
        ('Mustafa Khamis Machano','Saateni',2),
        ('Mwaka Ramadhani Vuai','Sebleni',2),
        ('Mwakutiani Abdalla Hassan','Sebleni',2),
        ('Nadra Rashid Omar','Mpendae',2),
        ('Rauhiya Kondo Abdalla','Sogea',2),
        ('Riziki Salum Ali','Mpendae',2),
        ('Sabrina Abdalla Ameir','Mpendae',2),
        ('Salma Jadid Omar','Muembe madema',2),
        ('Salma Salum Kheir','Muembe madema',2),
        ('Shuwena Muhsin Abdalla','Sogea',2),
        ('Tatu Othman Khalfan','Mpendae',2),
        ('Tatu Suleman Ameir','Sebleni',2),
        ('Thania Uwesu Ramadhani','Saateni',2),
        ('Wahida Omar Moh''D','Sogea',2),
        ('Zuhura Shaabani Hassan','Sogea',2),
        ('Abdisalam Hassan Bakari','Meya',2),
        ('Abdulrahman Tahir Ali','Shaurimoyo',2),
        ('Abuubakr Abdalla Hassan','Shaurimoyo',2),
        ('Adrophina Aletsandra Shabu','Meya',2),
        ('Ali Rashid Suleiman','Mlandege',2),
        ('Asha Makame Khamis','Shaurimoyo',2),
        ('Asha Seif Ali','Urusi',2),
        ('Dani Nasor Ahmed','Urusi',2),
        ('Fatma Juma Mohammed','Urusi',2),
        ('Hadiya Rashid Nassor','Mlandege',2),
        ('Halima Ali Mohamed','Mchangani',2),
        ('Hamza Jecha Nyange','Urusi',2),
        ('Hatiye Hamidu Mbuha','Meya',2),
        ('Ilham Awesu Iddi','Urusi',2),
        ('Kauthar Khamis Fakih','Mlandege',2),
        ('Kazija Ali Khamis','Shaurimoyo',2),
        ('Kazija Khamis Uledi','Meya',2),
        ('Khadija Abass Hassan','Mchangani',2),
        ('Khadija Khamis Fakih','Mlandege',2),
        ('Laila Ali Ramadhan','Urusi',2),
        ('Madina Said Abdallah','Urusi',2),
        ('Maryam Juma Othman','Urusi',2),
        ('Maryam Mussa Ali','Mchangani',2),
        ('Mohamed Twaha Hija','Shaurimoyo',2),
        ('Mtumwa Khamis Rashid','Meya',2),
        ('Mwajuma Silma Kuyu','Sahurimoyo',2),
        ('Mwanahija Kassim Ali','Meya',2),
        ('Mwanamrisho Ramadhan Haidar','Meya',2),
        ('Mwanapili Juma Chum','Urusi',2),
        ('Nadia Hija Kheri','Shaurimoyo',2),
        ('Niwaza Khamis Yagi','Meya',2),
        ('Nuru Mgeni Mwalim','Urusi',2),
        ('Raifa Mwalim Charuma','Urusi',2),
        ('Raya Said Kassim','Meya',2),
        ('Riziki Abdallah Mohammed','Meya',2),
        ('Said Omar Said','Urusi',2),
        ('Sheria Suleiman Abdallah','Urusi',2),
        ('Shumbana Ali Mshenga','Shaurimoyo',2),
        ('Thuwaiba Mussa Ally','Mchangani',2),
        ('Wanu Juma Rashid','Shaurimoyo',2),
        ('Zulekha Mohammed Khalfan','Shaurimoyo',2))
      AS u(name,shehia,"group")
  ),

  --Replacement CHVs who are placed in training and thus receiving flat stipend until end of April. 
  training_CTE AS (
    SELECT
      _id AS chv_uuid,
      name,
      shehia,
      retired,
      retirement_reason,
      reported_date AS doc_created_date,
      CASE
        WHEN reported_date BETWEEN '2021-11-29'::TIMESTAMP AND '2021-12-05'::TIMESTAMP
          THEN 'Yes' ELSE ''
      END AS still_in_training
    FROM useview_chv AS chv
    INNER JOIN useview_jna_locations AS location
      ON chv.catchment_area_uuid = location.catchment_area_uuid
  )

  SELECT
    training_CTE.chv_uuid,
    still_in_training,
    retired,
    retirement_reason,
    latest_replication_date AS latest_sync_date,
    first_reported_date AS first_visit_date,
    chv_payment_groups.group AS payment_group,
    CASE WHEN retired IS NOT NULL THEN coalesce(latest_reported_date,doc_created_date) END AS retirement_date
  FROM training_CTE
  LEFT JOIN useview_chv_latest_reported_date
    ON training_CTE.chv_uuid = useview_chv_latest_reported_date.chv_uuid
  LEFT JOIN useview_chv_sync
    ON training_CTE.chv_uuid = useview_chv_sync.chv_uuid
  LEFT JOIN chv_payment_groups
    ON training_CTE.name = chv_payment_groups.name
      AND training_CTE.shehia = chv_payment_groups.shehia
  LEFT JOIN chv_first_reported_date
    ON training_CTE.chv_uuid = chv_first_reported_date.chv_uuid
);

CREATE UNIQUE INDEX IF NOT EXISTS chv_uuid ON chv_status USING btree(chv_uuid);
ALTER MATERIALIZED VIEW chv_status OWNER TO full_access;
GRANT SELECT ON chv_status TO dtree;