---- catchment_area ---- 
DROP VIEW IF EXISTS gen_ai.catchment_area;
CREATE VIEW gen_ai.catchment_area AS (
  SELECT
    catchment._id,
    catchment._rev,
    catchment."name",
    catchment."type",
    catchment.supervisory_area_uuid,
    catchment.shehia,
    catchment.chv_uuid,
    catchment.imported_date,
    catchment.reported_date,
    catchment.retired,
    catchment.retirement_reason
  FROM public.useview_catchment_area AS catchment
  INNER JOIN public.useview_supervisory_area AS area
    ON area._id = catchment.supervisory_area_uuid
      AND district IN ('West B', 'Central')
);

---- chv ---- 
DROP VIEW IF EXISTS gen_ai.chv;
CREATE VIEW gen_ai.chv AS (
  SELECT
    chv._id,
    chv._rev,
    chv."type",
    chv.sex,
    chv.date_of_birth,
    chv.catchment_area_uuid,
    chv.supervisory_area_uuid,
    chv.imported_date,
    chv.reported_date,
    chv.retired,
    chv.retirement_reason,
    chv.projects
  FROM public.useview_chv AS chv
  INNER JOIN public.useview_supervisory_area AS area
    ON area._id = chv.supervisory_area_uuid
      AND district IN ('West B', 'Central')
);

---- household ---- 
DROP VIEW IF EXISTS gen_ai.household;
CREATE VIEW gen_ai.household AS (
  SELECT
    household._id,
    household._rev,
    household.catchment_area_uuid,
    household.supervisory_area_uuid,
    household.latitude,
    household.longitude,
    household.alititude,
    household.accuracy,
    household.contact_id,
    household.kitongoji,
    household.house_number,
    household.travel_time,
    household.means_of_travel,
    household.means_of_travel_other,
    household.number_hh_members,
    household.created_by,
    household.chv_uuid,
    household."type",
    household.reported_date
  FROM public.useview_household AS household
  INNER JOIN public.useview_supervisory_area AS area
    ON area._id = household.supervisory_area_uuid
      AND district IN ('West B', 'Central')
);

---- infant_child ---- 
DROP VIEW IF EXISTS gen_ai.infant_child;
CREATE VIEW gen_ai.infant_child AS (
  SELECT
    child._id,
    child._rev,
    child.form,
    child."type",
    child.content_type,
    child.reported_date,
    child.chv_uuid,
    child.catchment_area_uuid,
    child.supervisory_area_uuid,
    child.patient_id,
    child.child_sex,
    child.n_child_visits,
    child.child_date_of_birth,
    child.age_days,
    child.age_months,
    child.age_years,
    child.age_days_display,
    child.previous_small_baby,
    child.previous_bcg,
    child.previous_bopv0,
    child.previous_bopv1,
    child.previous_dtp_hepb_hib1,
    child.previous_pcvi1,
    child.previous_rota1,
    child.previous_bopv2,
    child.previous_dtp_hepb_hib2,
    child.previous_pcvi2,
    child.previous_rota2,
    child.previous_bopv3,
    child.previous_dtp_hepb_hib3,
    child.previous_pcvi3,
    child.previous_ipv,
    child.previous_surua_rubella1,
    child.previous_surua_rubella2,
    child.visit_id,
    child.due_date,
    child.due_date_pretty_print,
    child.household_head,
    child.house_number,
    child.kitongoji,
    child.start_time,
    child.end_time,
    child.child_consent_today,
    child.delivery_location,
    child.child_card_available,
    child.birthweight_on_child_card,
    child.child_birthweight,
    child.child_size_birth,
    child.small_baby_today,
    child.has_received_small_baby_services,
    child.refer_flag_small_baby,
    child.neonatal_not_able_feed,
    child.neonatal_had_convulsions,
    child.neonatal_difficulty_fast_breathing,
    child.neonatal_fever,
    child.neonatal_not_crying,
    child.neonatal_blue_color,
    child.neonatal_eyes_pus,
    child.neonatal_skin_boils,
    child.neonatal_excessive_vomiting,
    child.neonatal_excessive_crying,
    child.neonatal_severe_diarrhea,
    child.refer_neonatal_danger_sign_flag,
    child.neonatal_cold,
    child.neonatal_yellow_pale_palms,
    child.neonatal_no_movement,
    child.neonatal_cord_bleeding,
    child.neonatal_diarrhea,
    child.neonatal_eye_discharge,
    child.neonatal_skin_rash,
    child.neonatal_congenital,
    child.neonatal_vomiting,
    child.neonatal_bulging_fontanel,
    child.neonatal_abdominal_distension,
    child.neonatal_no_urine,
    child.neonatal_no_stool,
    child.refer_secondary_neonatal_danger_sign_flag,
    child.child_vomit,
    child.child_convulsions,
    child.child_lethargic,
    child.child_fever,
    child.child_difficulty_fast_breathing,
    child.child_severe_diarrhea,
    child.refer_child_danger_sign_flag,
    child.child_drink_below_6_months,
    child.child_drink_6_months_to_2_years,
    child.child_drink_above_2_years,
    child.child_coughing,
    child.child_cold,
    child.child_skin_boils,
    child.child_mild_diarrhea,
    child.refer_child_other_danger_sign_flag,
    child.growth_graph_range,
    child.muac_color,
    child.refer_muac_flag,
    child.palm_pallor,
    child.refer_palm_pallor_flag,
    child.diff_foods_should_give_child,
    child.food_varieties,
    child.food_variety_score,
    child.mny_solid_food_feed_child,
    child.small_baby_ever,
    child.is_hand_wash_important,
    child.selected_health_concerns,
    child.currently_breastfeeding,
    child.exclusively_breastfeeding,
    child.exclusive_breastfeeding_multiple_choice,
    child.is_breastfeeding_positioning_ok,
    child.suckling_effectively,
    child.ever_breastfed,
    child.time_to_breastfeed,
    child.baby_times_breastfed_daily,
    child.breastfeed_well,
    child.small_baby_other_than_breast_milk,
    child.still_breastfeeding,
    child.confirm_nutrition_counseling_c,
    child.has_health_card,
    child.received_bcg,
    child.bcg_date,
    child.received_bopv0,
    child.bopv0_date,
    child.received_bopv1,
    child.bopv1_date,
    child.received_dtp_hepb_hib1,
    child.dtp_hepb_hib1_date,
    child.received_pcvi1,
    child.pcvi1_date,
    child.received_rota1,
    child.rota1_date,
    child.received_bopv2,
    child.bopv2_date,
    child.received_dtp_hepb_hib2,
    child.dtp_hebp_hib2_date,
    child.received_pcvi2,
    child.pcvi2_date,
    child.received_rota2,
    child.rota2_date,
    child.received_bopv3,
    child.bopv3_date,
    child.received_dtp_hepb_hib3,
    child.dtp_hebp_hib3_date,
    child.received_pcvi3,
    child.pcvi3_date,
    child.received_ipv,
    child.ipv_date,
    child.received_surua_rubella1,
    child.surua_rubella1_date,
    child.received_surua_rubella2,
    child.surua_rubella2_date,
    child.vaccines_up_to_date,
    child.why_not_vaccines_up_to_date,
    child.refer_vaccines_flag,
    child.spend_time_with,
    child.who_joined_visit,
    child.father_first_visit,
    child.child_age_months,
    child.development_stage,
    child.how_play,
    child.how_communicate_lt_6mo,
    child.how_play_ge_6mo,
    child.how_communicate_ge_6mo,
    child.how_interact,
    child.has_observed_correcting,
    child.how_correct,
    child.does_caregiver_demonstrate_interaction,
    child.has_stress_concern_play_comm,
    child.has_time_concern_play_comm,
    child.engage_with_child,
    child.who_engages,
    child.who_engages_other,
    child.who_engages_how_many_hours_over_15,
    child.who_engages_how_many_hours,
    child.concern_toys,
    child.plays_with_toys_homemade,
    child.plays_with_toys_manufactured,
    child.plays_with_toys_household_objects,
    child.number_books,
    child.concern_leave_child,
    child.was_child_left_alone_more_than_1h,
    child.was_child_left_in_care_of_other_child_more_than_1h,
    child.concern_harsh_treatment,
    child.concern_stressful_family_environment,
    child.num_times_read_books,
    child.num_times_told_stories,
    child.num_times_sang_to_child,
    child.num_times_took_child_outside,
    child.num_times_played_with_child,
    child.num_times_drew_things,
    child.refer_stressful_environment_concern_flag,
    child.concern_slow_to_learn,
    child.slow_to_learn_delay_sitting,
    child.slow_to_learn_difficulty_seeing,
    child.slow_to_learn_difficulty_hearing,
    child.slow_to_learn_understand_speech,
    child.slow_to_learn_difficulty_walking_moving,
    child.slow_to_learn_has_fits,
    child.slow_to_learn_compared_with_kids,
    child.slow_to_learn_does_speak,
    child.slow_to_learn_speech_different,
    child.slow_to_learn_appears_mentally_backward,
    child.refer_slow_to_learn_specifics_flag,
    child.play_with_baby,
    child.talk_or_sing_with_baby,
    child.mention_ways_to_comfort_child,
    child.does_caregiver_interact_well_with_baby,
    child.caregiver_comfort_child,
    child.caregiver_comfort_ways,
    child.was_male_present,
    child.concern_see_or_hear,
    child.male_present_entire_visit,
    child.partner_interaction,
    child.has_latrine,
    child.latrine_type,
    child.has_mosquito_net,
    child.any_referral,
    child.latitude,
    child.longitude,
    child.altitude,
    child.accuracy
  FROM public.useview_infant_child AS child
  INNER JOIN public.useview_supervisory_area AS area
    ON area._id = child.supervisory_area_uuid
      AND district IN ('West B', 'Central')
);

---- person ---- 
DROP VIEW IF EXISTS gen_ai.person;
CREATE VIEW gen_ai.person AS (
  SELECT
    person._id,
    person._rev,
    person.sex,
    person.exact_dob_known,
    person.created_by_doc,
    person.date_of_birth,
    person.is_head_of_household,
    person.temp_hh_member,
    person.muted,
    person.date_of_death,
    person.created_by,
    person.chv_uuid,
    person.reported_date,
    person."type",
    person.household_uuid,
    person.catchment_area_uuid,
    person.supervisory_area_uuid
  FROM public.useview_person AS person
  INNER JOIN public.useview_supervisory_area AS area
    ON area._id = person.supervisory_area_uuid
      AND district IN ('West B', 'Central')
);

---- postpartum ---- 
DROP VIEW IF EXISTS gen_ai.postpartum;
CREATE VIEW gen_ai.postpartum AS (
  SELECT
    postpartum._id,
    postpartum._rev,
    postpartum.form,
    postpartum."type",
    postpartum.content_type,
    postpartum.reported_date,
    postpartum.chv_uuid,
    postpartum.catchment_area_uuid,
    postpartum.supervisory_area_uuid,
    postpartum.patient_id,
    postpartum.start_time,
    postpartum.end_time,
    postpartum.had_c_section,
    postpartum.date_of_birth_c,
    postpartum.age_days,
    postpartum.age_months,
    postpartum.age_years,
    postpartum.age_in_years,
    postpartum.age_days_display,
    postpartum.household_head,
    postpartum.house_number,
    postpartum.kitongoji,
    postpartum.due_date,
    postpartum.due_date_pretty_print,
    postpartum.show_research_questions,
    postpartum.show_quality_care_c,
    postpartum.visit_id,
    postpartum.is_atleast_one_baby_alive_c,
    postpartum.postpartum_severe_vaginal_bleeding,
    postpartum.postpartum_convulsions,
    postpartum.postpartum_unconscious,
    postpartum.postpartum_bleeding_right_now,
    postpartum.postpartum_pale_pallor,
    postpartum.postpartum_severe_frontal_headache,
    postpartum.postpartum_blurred_vision,
    postpartum.postpartum_urine,
    postpartum.postpartum_dizziness,
    postpartum.postpartum_exhaustion,
    postpartum.postpartum_severe_lower_abdominal_pain,
    postpartum.postpartum_vaginal_discharge,
    postpartum.postpartum_fever_chills,
    postpartum.postpartum_breathing_difficulty,
    postpartum.postpartum_severe_pain_foot,
    postpartum.postpartum_behavior,
    postpartum.postpartum_breast,
    postpartum.c_section_condition,
    postpartum.client_been_facility_3_days,
    postpartum.chv_thinks_needs_return_facility,
    postpartum.is_hand_wash_important,
    postpartum.selected_health_concerns,
    postpartum.has_attended_facility_pnc,
    postpartum.has_attended_facility_pnc_within_48hrs,
    postpartum.facility_pnc_date,
    postpartum.pnc_visit_count_zero,
    postpartum.quality_of_care_consent,
    postpartum.facility_island,
    postpartum.facility_district,
    postpartum.anc_visit_facility,
    postpartum.anc_visit_facility_other,
    postpartum.is_service_received,
    postpartum.no_service_reason,
    postpartum.second_facility,
    postpartum.pnc_services_received,
    postpartum.baby_services_recevied,
    postpartum.research_questions_consent,
    postpartum.travel_time,
    postpartum.travel_means,
    postpartum.other_means,
    postpartum.decision_maker,
    postpartum.some_other_decision_maker,
    postpartum.marital_status,
    postpartum.does_partner_live_together,
    postpartum.subgroup_partner_age,
    postpartum.partner_highest_school_level,
    postpartum.more_than_one_wife,
    postpartum.num_wives,
    postpartum.refer_postpartum_emergency_danger_sign_flag,
    postpartum.refer_postpartum_other_danger_sign_flag,
    postpartum.refer_postpartum_pnc_visit,
    postpartum.has_referral,
    postpartum.latitude,
    postpartum.longitude,
    postpartum.altitude,
    postpartum.accuracy
  FROM public.useview_postpartum AS postpartum
  INNER JOIN public.useview_supervisory_area AS area
    ON area._id = postpartum.supervisory_area_uuid
      AND district IN ('West B', 'Central')
);

---- pregnancy ---- 
DROP VIEW IF EXISTS gen_ai.pregnancy;
CREATE VIEW gen_ai.pregnancy AS (
  SELECT
    pregnancy._id,
    pregnancy._rev,
    pregnancy.form,
    pregnancy."type",
    pregnancy.content_type,
    pregnancy.reported_date,
    pregnancy.chv_uuid,
    pregnancy.catchment_area_uuid,
    pregnancy.supervisory_area_uuid,
    pregnancy.n_pregnancy_visits,
    pregnancy.n_previous_anc_visits,
    pregnancy.previous_hiv_status,
    pregnancy.previous_rchcard_status,
    pregnancy.show_research_questions,
    pregnancy.patient_id,
    pregnancy.date_of_birth_c,
    pregnancy.age_days,
    pregnancy.age_months,
    pregnancy.age_years,
    pregnancy.age_in_years,
    pregnancy.age_days_display,
    pregnancy.household_head,
    pregnancy.house_number,
    pregnancy.kitongoji,
    pregnancy.start_time,
    pregnancy.end_time,
    pregnancy.due_date,
    pregnancy.due_date_pretty_print_english,
    pregnancy.due_date_pretty_print_swahili,
    pregnancy.client_edd_pretty_print_english,
    pregnancy.client_edd_pretty_print_swahili,
    pregnancy.client_edd_c,
    pregnancy.currently_pregnant,
    pregnancy.hide_lmp_or_months_pregnant,
    pregnancy.visit_id,
    pregnancy.below_15_confirmation,
    pregnancy.above_49_confirmation,
    pregnancy.consent,
    pregnancy.highest_school_level,
    pregnancy.previous_uzazi_salama_enrollment,
    pregnancy.home_electricity,
    pregnancy.water_source,
    pregnancy.floor_material,
    pregnancy.roof_material,
    pregnancy.has_given_birth,
    pregnancy.viable_pregnancy,
    pregnancy.date_of_pregnancy_loss,
    pregnancy.miscarriage_or_stillbirth,
    pregnancy.first_time_pregnant,
    pregnancy.previous_pregnancies,
    pregnancy.previous_miscarriages,
    pregnancy.living_children,
    pregnancy.delivery_location,
    pregnancy.is_rch_card_available,
    pregnancy.is_delivery_date_written,
    pregnancy.estimated_delivery_date_input,
    pregnancy.remember_lmp,
    pregnancy.last_lmp_date,
    pregnancy.estimated_months_pregnant,
    pregnancy.edd,
    pregnancy.gestation_in_weeks,
    pregnancy.danger_sign_vaginal_bleeding,
    pregnancy.danger_sign_abdominal_pain,
    pregnancy.danger_sign_severe_headache,
    pregnancy.danger_sign_fever,
    pregnancy.danger_sign_unconsciouss,
    pregnancy.danger_sign_difficult_breathing,
    pregnancy.danger_sign_convulsions,
    pregnancy.emergency_danger_sign_referral,
    pregnancy.pregnancy_issues,
    pregnancy.refer_pregnancy_issues,
    pregnancy.baby_moving,
    pregnancy.pallor,
    pregnancy.refer_pregnancy_complications,
    pregnancy.hiv_test,
    pregnancy.disclose_hiv_status,
    pregnancy.hiv_status,
    pregnancy.take_art,
    pregnancy.family_engagement,
    pregnancy.num_anc_visits,
    pregnancy.anc_visit_count_zero,
    pregnancy.pregnancy_months_left,
    pregnancy.is_hand_wash_important,
    pregnancy.selected_health_concerns,
    pregnancy.has_mosquito_net,
    pregnancy.consent_for_questions,
    pregnancy.facility_island,
    pregnancy.facility_district,
    pregnancy.anc_visit_facility,
    pregnancy.anc_visit_facility_other,
    pregnancy.is_service_received,
    pregnancy.no_service_reason,
    pregnancy.second_facility,
    pregnancy.services_received,
    pregnancy.service_pay,
    pregnancy.amount_paid,
    pregnancy.paid_for,
    pregnancy.wait_period,
    pregnancy.recommendation_for_anc_visit,
    pregnancy.can_proceed_with_survey,
    pregnancy.travel_time,
    pregnancy.travel_means,
    pregnancy.other_means,
    pregnancy.decision_maker,
    pregnancy.some_other_decision_maker,
    pregnancy.marital_status,
    pregnancy.does_partner_live_together,
    pregnancy.subgroup_partner_age,
    pregnancy.partner_highest_school_level,
    pregnancy.more_than_one_wife,
    pregnancy.num_wives,
    pregnancy.has_referral,
    pregnancy.refer_flag_emergency_danger_sign,
    pregnancy.refer_flag_pregnancy_issues,
    pregnancy.refer_flag_pregnancy_complications,
    pregnancy.refer_flag_anc_visit,
    pregnancy.latitude,
    pregnancy.longitude,
    pregnancy.altitude,
    pregnancy.accuracy,
    pregnancy.is_allow_partner_to_deliver_facility,
    pregnancy.is_anemia_tablets,
    pregnancy.is_nutrition_restrictions,
    pregnancy.is_local_herbs,
    pregnancy.is_previous_delivery_by_c_section,
    pregnancy.is_previous_delivery_by_vacuum,
    pregnancy.is_previous_stillbirth,
    pregnancy.is_delivery_ten_or_more_years,
    pregnancy.is_big_baby,
    pregnancy.is_breech_position,
    pregnancy.is_higher_facility_delivery,
    pregnancy.is_malpresentation,
    pregnancy.is_multiple_pregnancy,
    pregnancy.delivery_complications,
    pregnancy.reason_no_tablets,
    pregnancy.medical_condition
  FROM public.useview_pregnancy AS pregnancy
  INNER JOIN public.useview_supervisory_area AS area
    ON area._id = pregnancy.supervisory_area_uuid
      AND district IN ('West B', 'Central')
);

---- pregnancy_outcomes ---- 
DROP VIEW IF EXISTS gen_ai.pregnancy_outcomes;
CREATE VIEW gen_ai.pregnancy_outcomes AS (
  SELECT
    pregnancy_outcomes._id,
    pregnancy_outcomes._rev,
    pregnancy_outcomes.form,
    pregnancy_outcomes."type",
    pregnancy_outcomes.content_type,
    pregnancy_outcomes.reported_date,
    pregnancy_outcomes.chv_uuid,
    pregnancy_outcomes.catchment_area_uuid,
    pregnancy_outcomes.supervisory_area_uuid,
    pregnancy_outcomes.household_uuid,
    pregnancy_outcomes.patient_id,
    pregnancy_outcomes.client_date_of_birth,
    pregnancy_outcomes.age_days,
    pregnancy_outcomes.age_months,
    pregnancy_outcomes.age_years,
    pregnancy_outcomes.age_days_display,
    pregnancy_outcomes.household_head,
    pregnancy_outcomes.house_number,
    pregnancy_outcomes.kitongoji,
    pregnancy_outcomes.start_time,
    pregnancy_outcomes.end_time,
    pregnancy_outcomes.client_edd,
    pregnancy_outcomes.pregnancy_outcome,
    pregnancy_outcomes.date_of_delivery,
    pregnancy_outcomes.date_of_pregnancy_loss,
    pregnancy_outcomes.miscarriage_or_stillbirth,
    pregnancy_outcomes.stillbirth_location,
    pregnancy_outcomes.delivery_location,
    pregnancy_outcomes.facility_island,
    pregnancy_outcomes.pnc_visit_island_other,
    pregnancy_outcomes.facility_district,
    pregnancy_outcomes.delivery_facility,
    pregnancy_outcomes.pnc_visit_facility_other,
    pregnancy_outcomes.facility_delivery_method,
    pregnancy_outcomes.home_delivery_helper,
    pregnancy_outcomes.got_facility_pnc,
    pregnancy_outcomes.refer_flag_no_facility_pnc,
    pregnancy_outcomes.born_early,
    pregnancy_outcomes.immediate_cry,
    pregnancy_outcomes.admitted_after_birth,
    pregnancy_outcomes.major_complications,
    pregnancy_outcomes.check_multiple_deliveries,
    pregnancy_outcomes.num_babies_delivered,
    pregnancy_outcomes.live_birth,
    pregnancy_outcomes.num_live_births,
    pregnancy_outcomes.child_death_count,
    pregnancy_outcomes.child_death_data,
    pregnancy_outcomes.child_repeat_count,
    pregnancy_outcomes.quality_of_care_consent,
    pregnancy_outcomes.how_handled_facility,
    pregnancy_outcomes.why_feel_handled_badly,
    pregnancy_outcomes.paid_delivery_fees,
    pregnancy_outcomes.purchased_supplies,
    pregnancy_outcomes.what_supplies_purchased,
    pregnancy_outcomes.would_recommend_facility,
    pregnancy_outcomes.latitude,
    pregnancy_outcomes.longitude,
    pregnancy_outcomes.altitude,
    pregnancy_outcomes.accuracy
  FROM public.useview_pregnancy_outcomes AS pregnancy_outcomes
  INNER JOIN public.useview_supervisory_area AS area
    ON area._id = pregnancy_outcomes.supervisory_area_uuid
      AND district IN ('West B', 'Central')
);

---- referral_follow_up ---- 
DROP VIEW IF EXISTS gen_ai.referral_follow_up;
CREATE VIEW gen_ai.referral_follow_up AS (
  SELECT
    referral_follow_up._id,
    referral_follow_up._rev,
    referral_follow_up.form,
    referral_follow_up."type",
    referral_follow_up.content_type,
    referral_follow_up.reported_date,
    referral_follow_up.chv_uuid,
    referral_follow_up.catchment_area_uuid,
    referral_follow_up.supervisory_area_uuid,
    referral_follow_up.patient_id,
    referral_follow_up.referral_source_form,
    referral_follow_up.referral_source_id,
    referral_follow_up.start_time,
    referral_follow_up.end_time,
    referral_follow_up.last_visit,
    referral_follow_up.last_visit_formatted,
    referral_follow_up.refer_flag_small_baby,
    referral_follow_up.refer_neonatal_danger_sign_flag,
    referral_follow_up.refer_secondary_neonatal_danger_sign_flag,
    referral_follow_up.refer_child_danger_sign_flag,
    referral_follow_up.refer_child_other_danger_sign_flag,
    referral_follow_up.refer_muac_flag,
    referral_follow_up.refer_palm_pallor_flag,
    referral_follow_up.refer_vaccines_flag,
    referral_follow_up.refer_slow_to_learn_specifics_flag,
    referral_follow_up.refer_flag_postpartum_danger_signs,
    referral_follow_up.refer_flag_postpartum_other_signs,
    referral_follow_up.refer_flag_postpartum_pnc_visit,
    referral_follow_up.refer_flag_anc_visit,
    referral_follow_up.refer_flag_pregnancy_danger_sign,
    referral_follow_up.refer_flag_pregnancy_issues,
    referral_follow_up.refer_flag_pregnancy_complications,
    referral_follow_up.client,
    referral_follow_up.client_date_of_birth,
    referral_follow_up.due_date,
    referral_follow_up.due_date_pretty_print,
    referral_follow_up.age_days,
    referral_follow_up.age_months,
    referral_follow_up.age_years,
    referral_follow_up.age_days_display,
    referral_follow_up.household_head,
    referral_follow_up.house_number,
    referral_follow_up.kitongoji,
    referral_follow_up.went_to_facility,
    referral_follow_up.went_to_facility_with_partner,
    referral_follow_up.got_services,
    referral_follow_up.reasons_no_services,
    referral_follow_up.reason_didnt_go,
    referral_follow_up.complete_referral,
    referral_follow_up.has_referral,
    referral_follow_up.referral_days,
    referral_follow_up.latitude,
    referral_follow_up.longitude,
    referral_follow_up.altitude,
    referral_follow_up.accuracy,
    referral_follow_up.follow_up_depth,
    referral_follow_up.original_source_form,
    referral_follow_up.original_source_form_uuid
  FROM public.useview_referral_follow_up AS referral_follow_up
  INNER JOIN public.useview_supervisory_area AS area
    ON area._id = referral_follow_up.supervisory_area_uuid
      AND district IN ('West B', 'Central')
);

---- supervisor ---- 
DROP VIEW IF EXISTS gen_ai.supervisor;
CREATE VIEW gen_ai.supervisor AS (
  SELECT
    supervisor._id,
    supervisor._rev,
    supervisor."type",
    supervisor.sex,
    supervisor.supervisory_area_uuid,
    supervisor.imported_date,
    supervisor.reported_date,
    supervisor.retired,
    supervisor.retirement_reason
  FROM public.useview_supervisor AS supervisor
  INNER JOIN public.useview_supervisory_area AS area
    ON area._id = supervisor.supervisory_area_uuid
      AND district IN ('West B', 'Central')
);

---- supervisory_area ---- 
DROP VIEW IF EXISTS gen_ai.supervisory_area;
CREATE VIEW gen_ai.supervisory_area AS (
  SELECT
    _id,
    _rev,
    "name",
    "type",
    supervisor_uuid,
    supervisor_reported_date,
    district,
    imported_date,
    reported_date
  FROM public.useview_supervisory_area
  WHERE district IN ('West B', 'Central')
);
