------------------------------------------------------------
-- Materialized view to show table of pregnancy forms.
------------------------------------------------------------
DROP MATERIALIZED VIEW IF EXISTS useview_pregnancy;

CREATE MATERIALIZED VIEW useview_pregnancy AS
(
  SELECT
    doc ->> '_id' AS _id,
    doc ->> '_rev' AS _rev,
    doc ->> 'form' AS form,
    doc ->> 'type' AS type,
    doc ->> 'content_type' AS content_type,
    to_timestamp(nullif(doc ->> 'reported_date', '')::DOUBLE PRECISION / 1000) AS reported_date,
    doc #>> '{contact,_id}' AS chv_uuid,
    doc #>> '{contact,parent,_id}' AS catchment_area_uuid,
    doc #>> '{contact,parent,parent,_id}' AS supervisory_area_uuid,
    doc ->> 'from' AS chv_phone,
    doc #>> '{fields,client_name}' AS client_name,
    nullif(nullif(doc #>> '{fields,n_pregnancy_visits}', 'NaN'), '')::INTEGER AS n_pregnancy_visits,
    nullif(nullif(doc #>> '{fields,n_previous_anc_visits}', 'NaN'), '')::INTEGER AS n_previous_anc_visits,
    nullif(doc #>> '{fields,previous_hiv_status}', '')::BOOLEAN AS previous_hiv_status,
    nullif(doc #>> '{fields,previous_rchcard_status}', '')::BOOLEAN AS previous_rchcard_status,
    nullif(doc #>> '{fields,show_research_questions}', '')::BOOLEAN AS show_research_questions,
    doc #>> '{fields,patient_id}' AS patient_id,
    doc #>> '{fields,created_by}' AS chv_name,
    to_date(nullif(doc #>> '{fields,date_of_birth_c}', ''), 'YYYY-MM-DD') AS date_of_birth_c,
    nullif(nullif(doc #>> '{fields,age_days}', 'NaN'), '')::INTEGER AS age_days,
    nullif(nullif(doc #>> '{fields,age_months}', 'NaN'), '')::INTEGER AS age_months,
    nullif(nullif(doc #>> '{fields,age_years}', 'NaN'), '')::INTEGER AS age_years,
    nullif(nullif(doc #>> '{fields,age_in_years}', 'NaN'), '')::INTEGER AS age_in_years,
    nullif(nullif(doc #>> '{fields,age_days_display}', 'NaN'), '')::INTEGER AS age_days_display,
    doc #>> '{fields,household_head}' AS household_head,
    doc #>> '{fields,house_number}' AS house_number,
    doc #>> '{fields,kitongoji}' AS kitongoji,
    doc #>> '{fields,phone}' AS phone,
    nullif(doc #>> '{fields,start}', '')::TIMESTAMP AS start_time,
    nullif(doc #>> '{fields,end}', '')::TIMESTAMP AS end_time,
    to_timestamp(nullif(doc #>> '{fields,due_date}', '')::DOUBLE PRECISION / 1000) AS due_date,
    doc #>> '{fields,due_date_pretty_print_english}' AS due_date_pretty_print_english,
    doc #>> '{fields,due_date_pretty_print_swahili}' AS due_date_pretty_print_swahili,
    doc #>> '{fields,client_EDD_pretty_print_english}' AS client_EDD_pretty_print_english,
    doc #>> '{fields,client_EDD_pretty_print_swahili}' AS client_EDD_pretty_print_swahili,
    to_date(nullif(doc #>> '{fields,client_EDD_c}', ''), 'YYYY-MM-DD') AS client_EDD_c,
    nullif(doc #>> '{fields,currently_pregnant}', '')::BOOLEAN AS currently_pregnant,
    nullif(doc #>> '{fields,hide_lmp_or_months_pregnant}', '')::BOOLEAN AS hide_lmp_or_months_pregnant,
    doc #>> '{fields,visit_id}' AS visit_id,
    nullif(doc #>> '{fields,age_below_15,below_15_confirmation}', '')::BOOLEAN AS below_15_confirmation,
    nullif(doc #>> '{fields,age_above_49,above_49_confirmation}', '')::BOOLEAN AS above_49_confirmation,
    nullif(doc #>> '{fields,pregnancy_consent,consent}', '')::BOOLEAN AS consent,
    doc #>> '{fields,education_and_prev_enrollment,highest_school_level}' AS highest_school_level,
    doc #>> '{fields,education_and_prev_enrollment,previous_uzazi_salama_enrollment}' AS previous_uzazi_salama_enrollment,
    doc #>> '{fields,education_and_prev_enrollment,home_electricity}' AS home_electricity,
    doc #>> '{fields,education_and_prev_enrollment,water_source}' AS water_source,
    doc #>> '{fields,education_and_prev_enrollment,floor_material}' AS floor_material,
    doc #>> '{fields,education_and_prev_enrollment,roof_material}' AS roof_material,
    nullif(doc #>> '{fields,visit_introduction,has_given_birth}', '')::BOOLEAN AS has_given_birth,
    nullif(doc #>> '{fields,visit_introduction,viable_pregnancy}', '')::BOOLEAN AS viable_pregnancy,
    to_date(nullif(doc #>> '{fields,visit_introduction,date_of_pregnancy_loss}', ''), 'YYYY-MM-DD') AS date_of_pregnancy_loss,
    doc #>> '{fields,visit_introduction,miscarriage_or_stillbirth}' AS miscarriage_or_stillbirth,
    nullif(doc #>> '{fields,pregnant_woman_information,first_time_pregnant}', '')::BOOLEAN AS first_time_pregnant,
    nullif(nullif(doc #>> '{fields,pregnant_woman_information,previous_pregnancies}', 'NaN'), '')::INTEGER AS previous_pregnancies,
    nullif(nullif(doc #>> '{fields,pregnant_woman_information,previous_miscarriages}', 'NaN'), '')::INTEGER AS previous_miscarriages,
    nullif(nullif(doc #>> '{fields,pregnant_woman_information,living_children}', 'NaN'), '')::INTEGER AS living_children,
    doc #>> '{fields,facility_delivery_importance,delivery_location}' AS delivery_location,
    nullif(doc #>> '{fields,rch_card,is_rch_card_available}', '')::BOOLEAN AS is_rch_card_available,
    nullif(doc #>> '{fields,rch_card,is_delivery_date_written}', '')::BOOLEAN AS is_delivery_date_written,
    to_date(nullif(doc #>> '{fields,rch_card,estimated_delivery_date_input}', ''), 'YYYY-MM-DD') AS estimated_delivery_date_input,
    doc #>> '{fields,rch_card,remember_lmp}' AS remember_lmp,
    to_date(nullif(doc #>> '{fields,rch_card,last_lmp_date}', ''), 'YYYY-MM-DD') AS last_lmp_date,
    nullif(nullif(doc #>> '{fields,rch_card,estimated_months_pregnant}', 'NaN'), '')::INTEGER AS estimated_months_pregnant,
    to_date(nullif(doc #>> '{fields,EDD}', ''), 'YYYY-MM-DD') AS EDD,
    nullif(nullif(doc #>> '{fields,gestation_in_weeks}', 'NaN'), '')::INTEGER AS gestation_in_weeks,
    nullif(doc #>> '{fields,danger_signs,danger_sign_table_1,danger_sign_vaginal_bleeding}', '')::BOOLEAN AS danger_sign_vaginal_bleeding,
    nullif(doc #>> '{fields,danger_signs,danger_sign_table_1,danger_sign_abdominal_pain}', '')::BOOLEAN AS danger_sign_abdominal_pain,
    nullif(doc #>> '{fields,danger_signs,danger_sign_table_1,danger_sign_severe_headache}', '')::BOOLEAN AS danger_sign_severe_headache,
    nullif(doc #>> '{fields,danger_signs,danger_sign_table_1,danger_sign_fever}', '')::BOOLEAN AS danger_sign_fever,
    nullif(doc #>> '{fields,danger_signs,danger_sign_table_2,danger_sign_unconsciouss}', '')::BOOLEAN AS danger_sign_unconsciouss,
    nullif(doc #>> '{fields,danger_signs,danger_sign_table_2,danger_sign_difficult_breathing}', '')::BOOLEAN AS danger_sign_difficult_breathing,
    nullif(doc #>> '{fields,danger_signs,danger_sign_table_2,danger_sign_convulsions}', '')::BOOLEAN AS danger_sign_convulsions,
    nullif(doc #>> '{fields,danger_signs,emergency_danger_sign_referral}', '')::BOOLEAN AS emergency_danger_sign_referral,
    doc #>> '{fields,pregnancy_issues_group,subgroup_pregnancy_issues,pregnancy_issues}' AS pregnancy_issues,
    nullif(doc #>> '{fields,pregnancy_issues_group,subgroup_pregnancy_issues,refer_pregnancy_issues}', '')::BOOLEAN AS refer_pregnancy_issues,
    nullif(doc #>> '{fields,pregnancy_issues_group,pregnancy_and_pallor,baby_moving}', '')::BOOLEAN AS baby_moving,
    nullif(doc #>> '{fields,pregnancy_issues_group,pregnancy_and_pallor,pallor}', '')::BOOLEAN AS pallor,
    nullif(doc #>> '{fields,pregnancy_issues_group,pregnancy_and_pallor,refer_pregnancy_complications}', '')::BOOLEAN AS refer_pregnancy_complications,
    nullif(doc #>> '{fields,pmtct,hiv_test}', '')::BOOLEAN AS hiv_test,
    nullif(doc #>> '{fields,pmtct,disclose_hiv_status}', '')::BOOLEAN AS disclose_hiv_status,
    doc #>> '{fields,pmtct,hiv_status}' AS hiv_status,
    nullif(doc #>> '{fields,pmtct,take_art}', '')::BOOLEAN AS take_art,
    doc #>> '{fields,fam_engagement,family_engagement}' AS family_engagement,
    nullif(nullif(doc #>> '{fields,anc_screening_and_counseling,num_anc_visits}', 'NaN'), '')::INTEGER AS num_anc_visits,
    doc #>> '{fields,anc_screening_and_counseling,anc_visit_count_zero}' AS anc_visit_count_zero,
    nullif(nullif(doc #>> '{fields,pregnancy_months_left}', 'NaN'), '')::INTEGER AS pregnancy_months_left,
    nullif(doc #>> '{fields,wash,subgroup_cleanliness,hand_wash_importance}','')::BOOLEAN AS is_hand_wash_important,
    nullif(doc #>> '{fields,wash,subgroup_health_concerns,health_concerns}','') AS selected_health_concerns,
    nullif(doc #>> '{fields,llints,mosquito_net_qn,has_mosquito_net}', '')::BOOLEAN AS has_mosquito_net,
    nullif(doc #>> '{fields,quality_of_survery_care,consent_for_questions}', '')::BOOLEAN AS consent_for_questions,
    doc #>> '{fields,quality_of_survery_care,facility_island}' AS facility_island,
    doc #>> '{fields,quality_of_survery_care,facility_district}' AS facility_district,
    doc #>> '{fields,quality_of_survery_care,subgroup_facility_delivery,anc_visit_facility}' AS anc_visit_facility,
    doc #>> '{fields,quality_of_survery_care,subgroup_facility_delivery,anc_visit_facility_other}' AS anc_visit_facility_other,
    doc #>> '{fields,quality_of_survery_care,is_service_received}' AS is_service_received,
    doc #>> '{fields,quality_of_survery_care,no_service_reason}' AS no_service_reason,
    doc #>> '{fields,quality_of_survery_care,second_facility}' AS second_facility,
    doc #>> '{fields,quality_of_survery_care,services_received}' AS services_received,
    nullif(doc #>> '{fields,quality_of_survery_care,service_pay}', '')::BOOLEAN AS service_pay,
    nullif(nullif(doc #>> '{fields,quality_of_survery_care,amount_paid}', 'NaN'), '')::INTEGER AS amount_paid,
    doc #>> '{fields,quality_of_survery_care,paid_for}' AS paid_for,
    doc #>> '{fields,quality_of_survery_care,wait_period}' AS wait_period,
    nullif(doc #>> '{fields,quality_of_survery_care,recommendation_for_anc_visit}', '')::BOOLEAN AS recommendation_for_anc_visit,
    nullif(doc #>> '{fields,personal_information,can_proceed_with_survey}', '')::BOOLEAN AS can_proceed_with_survey,
    doc #>> '{fields,personal_information,travel_time}' AS travel_time,
    doc #>> '{fields,personal_information,transport,travel_means}' AS travel_means,
    doc #>> '{fields,personal_information,transport,other_means}' AS other_means,
    doc #>> '{fields,personal_information,subgroup_decision_maker,decision_maker}' AS decision_maker,
    doc #>> '{fields,personal_information,subgroup_decision_maker,some_other_decision_maker}' AS some_other_decision_maker,
    doc #>> '{fields,personal_information,subgroup_marital_status,marital_status}' AS marital_status,
    doc #>> '{fields,personal_information,subgroup_partner_info,does_partner_live_together}' AS does_partner_live_together,
    nullif(nullif(doc #>> '{fields,personal_information,partner_info,subgroup_partner_age}', 'NaN'), '')::INTEGER AS subgroup_partner_age,
    doc #>> '{fields,personal_information,partner_info,partner_highest_school_level}' AS partner_highest_school_level,
    doc #>> '{fields,personal_information,subgroup_multiple_wives,more_than_one_wife}' AS more_than_one_wife,
    nullif(nullif(doc #>> '{fields,personal_information,subgroup_multiple_wives,num_wives}', 'NaN'), '')::INTEGER AS num_wives,
    nullif(doc #>> '{fields,has_referral}', '')::BOOLEAN AS has_referral,
    nullif(doc #>> '{fields,refer_flag_emergency_danger_sign}', '')::BOOLEAN AS refer_flag_emergency_danger_sign,
    nullif(doc #>> '{fields,refer_flag_pregnancy_issues}', '')::BOOLEAN AS refer_flag_pregnancy_issues,
    nullif(doc #>> '{fields,refer_flag_pregnancy_complications}', '')::BOOLEAN AS refer_flag_pregnancy_complications,
    nullif(doc #>> '{fields,refer_flag_anc_visit}', '')::BOOLEAN AS refer_flag_anc_visit,
    nullif(doc #>> '{geolocation,latitude}', '')::DECIMAL AS latitude,
    nullif(doc #>> '{geolocation,longitude}', '')::DECIMAL AS longitude,
    nullif(doc #>> '{geolocation,altitude}', '')::DECIMAL AS altitude,
    nullif(doc #>> '{geolocation,accuracy}', '')::DECIMAL AS accuracy,
    nullif(doc #>> '{fields,facility_delivery_importance,allow_partner_to_deliver_facility}','')::BOOLEAN AS is_allow_partner_to_deliver_facility,
    nullif(doc #>> '{fields,maternal_nutrition,anemia_tablets}','')::BOOLEAN AS is_anemia_tablets,
    nullif(doc #>> '{fields,maternal_nutrition,nutrition_restrictions}','')::BOOLEAN AS is_nutrition_restrictions,
    nullif(doc #>> '{fields,pregnant_woman_information,local_herbs}','')::BOOLEAN AS is_local_herbs,
    nullif(doc #>> '{fields,pregnant_woman_information,previous_delivery_by_c_section}','')::BOOLEAN AS is_previous_delivery_by_c_section,
    nullif(doc #>> '{fields,pregnant_woman_information,previous_delivery_by_vacuum}','')::BOOLEAN AS is_previous_delivery_by_vacuum,
    nullif(doc #>> '{fields,pregnant_woman_information,previous_stillbirth}','')::BOOLEAN AS is_previous_stillbirth,
    nullif(doc #>> '{fields,pregnant_woman_information,ten_or_more_years}','')::BOOLEAN AS is_delivery_ten_or_more_years,
    nullif(doc #>> '{fields,rch_card,big_baby}','')::BOOLEAN AS is_big_baby,
    nullif(doc #>> '{fields,rch_card,breech_position}','')::BOOLEAN AS is_breech_position,
    nullif(doc #>> '{fields,rch_card,higher_facility_delivery}','')::BOOLEAN AS is_higher_facility_delivery,
    nullif(doc #>> '{fields,rch_card,malpresentation}','')::BOOLEAN AS is_malpresentation,
    nullif(doc #>> '{fields,rch_card,multiple_pregnancy}','')::BOOLEAN AS is_multiple_pregnancy,
    doc #>> '{fields,pregnant_woman_information,delivery_complications}' AS delivery_complications,
    doc #>> '{fields,maternal_nutrition,reason_no_tablets}' AS reason_no_tablets,
    doc #>> '{fields,rch_card,medical_condition}' AS medical_condition
  FROM
    couchdb
  WHERE
    doc ->> 'form' = 'pregnancy'
);

CREATE UNIQUE INDEX IF NOT EXISTS pregnancy_reported_date_created_by_uuid ON useview_pregnancy USING btree(reported_date, chv_uuid, patient_id);
-- Permissions
ALTER MATERIALIZED VIEW useview_pregnancy OWNER TO full_access;
GRANT SELECT ON useview_pregnancy TO dtree, periscope;
