------------------------------------------------------------
-- Materialized view to show table of postpartum forms.
------------------------------------------------------------
DROP MATERIALIZED VIEW IF EXISTS useview_postpartum;

CREATE MATERIALIZED VIEW useview_postpartum AS
(
  SELECT
    doc ->> '_id' AS _id,
    doc ->> '_rev' AS _rev,
    doc ->> 'form' AS form,
    doc ->> 'type' AS type,
    doc ->> 'content_type' AS content_type,
    to_timestamp(nullif(doc ->> 'reported_date', '')::DOUBLE PRECISION / 1000) AS reported_date,
    doc #>> '{contact,_id}' AS chv_uuid,
    doc #>> '{contact,parent,_id}' AS catchment_area_uuid,
    doc #>> '{contact,parent,parent,_id}' AS supervisory_area_uuid,
    doc ->> 'from' AS chv_phone,
    doc #>> '{fields,client_name}' AS client_name,
    doc #>> '{fields,patient_id}' AS patient_id,
    doc #>> '{fields,created_by}' AS chv_name,
    nullif(doc #>> '{fields,start}', '')::TIMESTAMP AS start_time,
    nullif(doc #>> '{fields,end}', '')::TIMESTAMP AS end_time,
    nullif(doc #>> '{fields,had_c_section}', '')::BOOLEAN AS had_c_section,
    to_date(nullif(doc #>> '{fields,date_of_birth_c}', ''), 'YYYY-MM-DD') AS date_of_birth_c,
    nullif(nullif(doc #>> '{fields,age_days}', 'NaN'), '')::INTEGER AS age_days,
    nullif(nullif(doc #>> '{fields,age_months}', 'NaN'), '')::INTEGER AS age_months,
    nullif(nullif(doc #>> '{fields,age_years}', 'NaN'), '')::INTEGER AS age_years,
    nullif(nullif(doc #>> '{fields,age_in_years}', 'NaN'), '')::INTEGER AS age_in_years,
    nullif(nullif(doc #>> '{fields,age_days_display}', 'NaN'), '')::INTEGER AS age_days_display,
    doc #>> '{fields,household_head}' AS household_head,
    doc #>> '{fields,house_number}' AS house_number,
    doc #>> '{fields,kitongoji}' AS kitongoji,
    doc #>> '{fields,phone}' AS phone,
    to_timestamp(nullif(doc #>> '{fields,due_date}', '')::DOUBLE PRECISION / 1000) AS due_date,
    doc #>> '{fields,due_date_pretty_print}' AS due_date_pretty_print,
    nullif(doc #>> '{fields,show_research_questions}', '')::BOOLEAN AS show_research_questions,
    nullif(doc #>> '{fields,show_quality_care_c}', '')::BOOLEAN AS show_quality_care_c,
    doc #>> '{fields,visit_id}' AS visit_id,
    nullif(doc #>> '{fields,is_atleast_one_baby_alive_c}', '')::BOOLEAN AS is_atleast_one_baby_alive_c,
    nullif(doc #>> '{fields,postpartum_danger_signs,postpartum_emergency_danger_signs,postpartum_emergency_danger_signs_table,postpartum_severe_vaginal_bleeding}', '')::BOOLEAN AS postpartum_severe_vaginal_bleeding,
    nullif(doc #>> '{fields,postpartum_danger_signs,postpartum_emergency_danger_signs,postpartum_emergency_danger_signs_table,postpartum_convulsions}', '')::BOOLEAN AS postpartum_convulsions,
    nullif(doc #>> '{fields,postpartum_danger_signs,postpartum_emergency_danger_signs,postpartum_emergency_danger_signs_table,postpartum_unconscious}', '')::BOOLEAN AS postpartum_unconscious,
    nullif(doc #>> '{fields,postpartum_danger_signs,postpartum_emergency_danger_signs,postpartum_bleeding_right_now}', '')::BOOLEAN AS postpartum_bleeding_right_now,
    nullif(doc #>> '{fields,postpartum_other_danger_signs,postpartum_other_danger_signs_table,postpartum_pale_pallor}', '')::BOOLEAN AS postpartum_pale_pallor,
    nullif(doc #>> '{fields,postpartum_other_danger_signs,postpartum_other_danger_signs_table,postpartum_severe_frontal_headache}', '')::BOOLEAN AS postpartum_severe_frontal_headache,
    nullif(doc #>> '{fields,postpartum_other_danger_signs,postpartum_other_danger_signs_table,postpartum_blurred_vision}', '')::BOOLEAN AS postpartum_blurred_vision,
    nullif(doc #>> '{fields,postpartum_other_danger_signs,postpartum_other_danger_signs_table,postpartum_urine}', '')::BOOLEAN AS postpartum_urine,
    nullif(doc #>> '{fields,postpartum_other_danger_signs,postpartum_other_danger_signs_table,postpartum_dizziness}', '')::BOOLEAN AS postpartum_dizziness,
    nullif(doc #>> '{fields,postpartum_other_danger_signs,postpartum_other_danger_signs_table,postpartum_exhaustion}', '')::BOOLEAN AS postpartum_exhaustion,
    nullif(doc #>> '{fields,postpartum_other_danger_signs,postpartum_other_danger_signs_table,postpartum_severe_lower_abdominal_pain}', '')::BOOLEAN AS postpartum_severe_lower_abdominal_pain,
    nullif(doc #>> '{fields,postpartum_other_danger_signs,postpartum_other_danger_signs_table,postpartum_vaginal_discharge}', '')::BOOLEAN AS postpartum_vaginal_discharge,
    nullif(doc #>> '{fields,postpartum_other_danger_signs,postpartum_other_danger_signs_table,postpartum_fever_chills}', '')::BOOLEAN AS postpartum_fever_chills,
    nullif(doc #>> '{fields,postpartum_other_danger_signs,postpartum_other_danger_signs_table,postpartum_breathing_difficulty}', '')::BOOLEAN AS postpartum_breathing_difficulty,
    nullif(doc #>> '{fields,postpartum_other_danger_signs,postpartum_other_danger_signs_table,postpartum_severe_pain_foot}', '')::BOOLEAN AS postpartum_severe_pain_foot,
    nullif(doc #>> '{fields,postpartum_other_danger_signs,postpartum_other_danger_signs_table,postpartum_behavior}', '')::BOOLEAN AS postpartum_behavior,
    nullif(doc #>> '{fields,postpartum_other_danger_signs,postpartum_other_danger_signs_table,postpartum_breast}', '')::BOOLEAN AS postpartum_breast,
    doc #>> '{fields,postpartum_other_danger_signs,c_section_condition}' AS c_section_condition,
    nullif(doc #>> '{fields,postpartum_other_danger_signs,client_been_facility_3_days}', '')::BOOLEAN AS client_been_facility_3_days,
    nullif(doc #>> '{fields,postpartum_other_danger_signs,chv_thinks_needs_return_facility}', '')::BOOLEAN AS chv_thinks_needs_return_facility,
    nullif(doc #>> '{fields,wash,subgroup_cleanliness,hand_wash_importance}','')::BOOLEAN AS is_hand_wash_important,
    nullif(doc #>> '{fields,wash,subgroup_health_concerns,health_concerns}','') AS selected_health_concerns,
    nullif(doc #>> '{fields,check_facility_pnc,has_attended_facility_pnc}', '')::BOOLEAN AS has_attended_facility_pnc,
    nullif(doc #>> '{fields,check_facility_pnc,has_attended_facility_pnc_within_48hrs}', '')::BOOLEAN AS has_attended_facility_pnc_within_48hrs,
    to_date(doc #>> '{fields,check_facility_pnc,facility_pnc_date}', 'YYYY-MM-DD') AS facility_pnc_date,
    doc #>> '{fields,check_facility_pnc,pnc_visit_count_zero}' AS pnc_visit_count_zero,
    nullif(doc #>> '{fields,check_facility_pnc,quality_of_care_consent}', '')::BOOLEAN AS quality_of_care_consent,
    doc #>> '{fields,quality_of_care,facility_island}' AS facility_island,
    doc #>> '{fields,quality_of_care,facility_district}' AS facility_district,
    doc #>> '{fields,quality_of_care,subgroup_facility,anc_visit_facility}' AS anc_visit_facility,
    doc #>> '{fields,quality_of_care,subgroup_facility,anc_visit_facility_other}' AS anc_visit_facility_other,
    doc #>> '{fields,quality_of_care,is_service_received}' AS is_service_received,
    doc #>> '{fields,quality_of_care,no_service_reason}' AS no_service_reason,
    doc #>> '{fields,quality_of_care,second_facility}' AS second_facility,
    doc #>> '{fields,quality_of_care,pnc_services_received}' AS pnc_services_received,
    doc #>> '{fields,quality_of_care,baby_services_recevied}' AS baby_services_recevied,
    nullif(doc #>> '{fields,personal_information_consent,research_questions_consent}', '')::BOOLEAN AS research_questions_consent,
    doc #>> '{fields,research_questions,travel_time}' AS travel_time,
    doc #>> '{fields,research_questions,transport,travel_means}' AS travel_means,
    doc #>> '{fields,research_questions,transport,other_means}' AS other_means,
    doc #>> '{fields,research_questions,subgroup_decision_maker,decision_maker}' AS decision_maker,
    doc #>> '{fields,research_questions,subgroup_decision_maker,some_other_decision_maker}' AS some_other_decision_maker,
    doc #>> '{fields,research_questions,subgroup_marital_status,marital_status}' AS marital_status,
    doc #>> '{fields,research_questions,subgroup_partner_info,does_partner_live_together}' AS does_partner_live_together,
    nullif(nullif(doc #>> '{fields,research_questions,partner_info,subgroup_partner_age}', 'NaN'), '')::INTEGER AS subgroup_partner_age,
    doc #>> '{fields,research_questions,partner_info,partner_highest_school_level}' AS partner_highest_school_level,
    doc #>> '{fields,research_questions,subgroup_multiple_wives,more_than_one_wife}' AS more_than_one_wife,
    nullif(nullif(doc #>> '{fields,research_questions,subgroup_multiple_wives,num_wives}', 'NaN'), '')::INTEGER AS num_wives,
    nullif(doc #>> '{fields,refer_postpartum_emergency_danger_sign_flag}', '')::BOOLEAN AS refer_postpartum_emergency_danger_sign_flag,
    nullif(doc #>> '{fields,refer_postpartum_other_danger_sign_flag}', '')::BOOLEAN AS refer_postpartum_other_danger_sign_flag,
    nullif(doc #>> '{fields,refer_postpartum_pnc_visit}', '')::BOOLEAN AS refer_postpartum_pnc_visit,
    nullif(doc #>> '{fields,has_referral}', '')::BOOLEAN AS has_referral,
    nullif(doc #>> '{geolocation,latitude}', '')::DECIMAL AS latitude,
    nullif(doc #>> '{geolocation,longitude}', '')::DECIMAL AS longitude,
    nullif(doc #>> '{geolocation,altitude}', '')::DECIMAL AS altitude,
    nullif(doc #>> '{geolocation,accuracy}', '')::DECIMAL AS accuracy
  FROM
    couchdb
  WHERE
    doc ->> 'form' = 'postpartum'
);

CREATE UNIQUE INDEX IF NOT EXISTS postpartum_reported_date_created_by_uuid ON useview_postpartum USING btree(reported_date, chv_uuid, patient_id);
-- Permissions
ALTER MATERIALIZED VIEW useview_postpartum OWNER TO full_access;
GRANT SELECT ON useview_postpartum TO full_access, dtree, periscope;