------------------------------------------------------------
-- Materialized view to show table of infant_child forms.
------------------------------------------------------------
DROP MATERIALIZED VIEW IF EXISTS useview_infant_child;

CREATE MATERIALIZED VIEW useview_infant_child AS 
(
  SELECT
    doc ->> '_id' AS _id,
    doc ->> '_rev' AS _rev,
    doc ->> 'form' AS form,
    doc ->> 'type' AS type,
    doc ->> 'content_type' AS content_type,
    TO_TIMESTAMP((NULLIF(doc ->> 'reported_date', '')::BIGINT / 1000)::DOUBLE PRECISION) AS reported_date,
    doc #>> '{contact,_id}' AS chv_uuid,
    doc #>> '{contact,parent,_id}' AS catchment_area_uuid,
    doc #>> '{contact,parent,parent,_id}' AS supervisory_area_uuid,
    doc ->> 'from' AS chv_phone,
    doc #>> '{fields,patient_id}' AS patient_id,
    doc #>> '{fields,child_name}' AS child_name,
    doc #>> '{fields,inputs,contact,sex}' AS child_sex,
    NULLIF(doc #>> '{fields,n_child_visits}', '')::INTEGER AS n_child_visits,
    TO_DATE(doc #>> '{fields,child_date_of_birth}', 'YYYY-MM-DD') AS child_date_of_birth,
    NULLIF(doc #>> '{fields,age_days}', '')::DECIMAL AS age_days,
    NULLIF(doc #>> '{fields,age_months}', '')::INTEGER AS age_months,
    NULLIF(doc #>> '{fields,age_years}', '')::INTEGER AS age_years,
    NULLIF(doc #>> '{fields,age_days_display}', '')::INTEGER AS age_days_display,
    NULLIF(doc #>> '{fields,previous_small_baby}', '')::BOOLEAN AS previous_small_baby,
    NULLIF(doc #>> '{fields,previous_bcg}', '')::BOOLEAN AS previous_bcg,
    NULLIF(doc #>> '{fields,previous_bopv0}', '')::BOOLEAN AS previous_bopv0,
    NULLIF(doc #>> '{fields,previous_bopv1}', '')::BOOLEAN AS previous_bopv1,
    NULLIF(doc #>> '{fields,previous_dtp_hepb_hib1}', '')::BOOLEAN AS previous_dtp_hepb_hib1,
    NULLIF(doc #>> '{fields,previous_pcvi1}', '')::BOOLEAN AS previous_pcvi1,
    NULLIF(doc #>> '{fields,previous_rota1}', '')::BOOLEAN AS previous_rota1,
    NULLIF(doc #>> '{fields,previous_bopv2}', '')::BOOLEAN AS previous_bopv2,
    NULLIF(doc #>> '{fields,previous_dtp_hepb_hib2}', '')::BOOLEAN AS previous_dtp_hepb_hib2,
    NULLIF(doc #>> '{fields,previous_pcvi2}', '')::BOOLEAN AS previous_pcvi2,
    NULLIF(doc #>> '{fields,previous_rota2}', '')::BOOLEAN AS previous_rota2,
    NULLIF(doc #>> '{fields,previous_bopv3}', '')::BOOLEAN AS previous_bopv3,
    NULLIF(doc #>> '{fields,previous_dtp_hepb_hib3}', '')::BOOLEAN AS previous_dtp_hepb_hib3,
    NULLIF(doc #>> '{fields,previous_pcvi3}', '')::BOOLEAN AS previous_pcvi3,
    NULLIF(doc #>> '{fields,previous_ipv}', '')::BOOLEAN AS previous_ipv,
    NULLIF(doc #>> '{fields,previous_surua_rubella1}', '')::BOOLEAN AS previous_surua_rubella1,
    NULLIF(doc #>> '{fields,previous_surua_rubella2}', '')::BOOLEAN AS previous_surua_rubella2,
    doc #>> '{fields,visit_id}' AS visit_id,
    TO_TIMESTAMP((NULLIF(doc #>> '{fields,due_date}', '')::BIGINT / 1000)::DOUBLE PRECISION) AS due_date,
    doc #>> '{fields,due_date_pretty_print}' AS due_date_pretty_print,
    doc #>> '{fields,created_by}' AS chv_name,
    doc #>> '{fields,household_head}' AS household_head,
    doc #>> '{fields,house_number}' AS house_number,
    doc #>> '{fields,kitongoji}' AS kitongoji,
    doc #>> '{fields,phone}' AS phone,
    NULLIF(doc #>> '{fields,start}', '')::TIMESTAMP as start_time,
    NULLIF(doc #>> '{fields,end}', '')::TIMESTAMP as end_time,
    NULLIF(doc #>> '{fields,consent,child_consent_today}', '')::BOOLEAN AS child_consent_today,
    doc #>> '{fields,first_visit_6_months,delivery_location}' AS delivery_location,
    NULLIF(doc #>> '{fields,first_visit_6_months,child_card_available}', '')::BOOLEAN AS child_card_available,
    NULLIF(doc #>> '{fields,first_visit_6_months,birthweight_on_child_card}', '')::BOOLEAN AS birthweight_on_child_card,
    NULLIF(doc #>> '{fields,first_visit_6_months,child_birthweight}', '')::DECIMAL AS child_birthweight,
    doc #>> '{fields,first_visit_6_months,child_size_birth}' AS child_size_birth,
    NULLIF(doc #>> '{fields,first_visit_6_months,small_baby_today}', '')::BOOLEAN AS small_baby_today,
    NULLIF(doc #>> '{fields,first_visit_6_months,has_received_small_baby_services}', '')::BOOLEAN AS has_received_small_baby_services,
    NULLIF(doc #>> '{fields,first_visit_6_months,refer_flag_small_baby}', '')::BOOLEAN AS refer_flag_small_baby,
    NULLIF(doc #>> '{fields,neonatal_danger_signs,neonatal_not_able_feed}', '')::BOOLEAN AS neonatal_not_able_feed,
    NULLIF(doc #>> '{fields,neonatal_danger_signs,neonatal_had_convulsions}', '')::BOOLEAN AS neonatal_had_convulsions,
    NULLIF(doc #>> '{fields,neonatal_danger_signs,neonatal_difficulty_fast_breathing}', '')::BOOLEAN AS neonatal_difficulty_fast_breathing,
    NULLIF(doc #>> '{fields,neonatal_danger_signs,neonatal_fever}', '')::BOOLEAN AS neonatal_fever,
    NULLIF(COALESCE(doc #>> '{fields,neonatal_danger_signs,neonatal_not_crying}',doc #>> '{fields,neonatal_danger_signs_secondary,neonatal_not_crying}'),'')::BOOLEAN AS neonatal_not_crying,
    NULLIF(COALESCE(doc #>> '{fields,neonatal_danger_signs,neonatal_blue_color}',doc #>> '{fields,neonatal_danger_signs_secondary,neonatal_blue_color}'),'')::BOOLEAN AS neonatal_blue_color,
    NULLIF(doc #>> '{fields,neonatal_danger_signs,neonatal_eyes_pus}', '')::BOOLEAN AS neonatal_eyes_pus,
    NULLIF(doc #>> '{fields,neonatal_danger_signs,neonatal_skin_boils}', '')::BOOLEAN AS neonatal_skin_boils,
    NULLIF(doc #>> '{fields,neonatal_danger_signs,neonatal_excessive_vomiting}', '')::BOOLEAN AS neonatal_excessive_vomiting,
    NULLIF(doc #>> '{fields,neonatal_danger_signs,neonatal_excessive_crying}', '')::BOOLEAN AS neonatal_excessive_crying,
    NULLIF(doc #>> '{fields,neonatal_danger_signs,neonatal_severe_diarrhea}', '')::BOOLEAN AS neonatal_severe_diarrhea,
    NULLIF(doc #>> '{fields,neonatal_danger_signs,refer_neonatal_danger_sign_flag}', '')::BOOLEAN AS refer_neonatal_danger_sign_flag,
    NULLIF(COALESCE(doc #>> '{fields,neonatal_danger_signs_secondary,neonatal_cold}', doc #>> '{fields,neonatal_danger_signs,neonatal_cold}'),'')::BOOLEAN AS neonatal_cold,
    NULLIF(COALESCE(doc #>> '{fields,neonatal_danger_signs_secondary,neonatal_yellow_pale_palms}',doc #>> '{fields,neonatal_danger_signs,neonatal_yellow_pale_palms}'),'')::BOOLEAN AS neonatal_yellow_pale_palms,
    NULLIF(COALESCE(doc #>> '{fields,neonatal_danger_signs_secondary,neonatal_no_movement}', doc #>> '{fields,neonatal_danger_signs,neonatal_no_movement}'),'')::BOOLEAN AS neonatal_no_movement,
    NULLIF(COALESCE(doc #>> '{fields,neonatal_danger_signs_secondary,neonatal_cord_bleeding}', doc #>> '{fields,neonatal_danger_signs,neonatal_cord_bleeding}'),'')::BOOLEAN AS neonatal_cord_bleeding,
    NULLIF(COALESCE(doc #>> '{fields,neonatal_danger_signs_secondary,neonatal_diarrhea}', doc #>> '{fields,neonatal_danger_signs,neonatal_diarrhea}'),'')::BOOLEAN AS neonatal_diarrhea,
    NULLIF(doc #>> '{fields,neonatal_danger_signs_secondary,neonatal_eye_discharge}', '')::BOOLEAN AS neonatal_eye_discharge,
    NULLIF(doc #>> '{fields,neonatal_danger_signs_secondary,neonatal_skin_rash}', '')::BOOLEAN AS neonatal_skin_rash,
    NULLIF(doc #>> '{fields,neonatal_danger_signs_secondary,neonatal_congenital}', '')::BOOLEAN AS neonatal_congenital,
    NULLIF(doc #>> '{fields,neonatal_danger_signs_secondary,neonatal_vomiting}', '')::BOOLEAN AS neonatal_vomiting,
    NULLIF(doc #>> '{fields,neonatal_danger_signs_secondary,neonatal_bulging_fontanel}', '')::BOOLEAN AS neonatal_bulging_fontanel,
    NULLIF(doc #>> '{fields,neonatal_danger_signs_secondary,neonatal_abdominal_distension}', '')::BOOLEAN AS neonatal_abdominal_distension,
    NULLIF(doc #>> '{fields,neonatal_danger_signs_secondary,neonatal_no_urine}', '')::BOOLEAN AS neonatal_no_urine,
    NULLIF(doc #>> '{fields,neonatal_danger_signs_secondary,neonatal_no_stool}', '')::BOOLEAN AS neonatal_no_stool,
    NULLIF(doc #>> '{fields,neonatal_danger_signs_secondary,refer_secondary_neonatal_danger_sign_flag}', '')::BOOLEAN AS refer_secondary_neonatal_danger_sign_flag,
    NULLIF(doc #>> '{fields,child_danger_signs,child_vomit}', '')::BOOLEAN AS child_vomit,
    NULLIF(doc #>> '{fields,child_danger_signs,child_convulsions}', '')::BOOLEAN AS child_convulsions,
    NULLIF(doc #>> '{fields,child_danger_signs,child_lethargic}', '')::BOOLEAN AS child_lethargic,
    NULLIF(doc #>> '{fields,child_danger_signs,child_fever}', '')::BOOLEAN AS child_fever,
    NULLIF(doc #>> '{fields,child_danger_signs,child_difficulty_fast_breathing}', '')::BOOLEAN AS child_difficulty_fast_breathing,
    NULLIF(COALESCE(doc #>> '{fields,child_danger_signs,child_severe_diarrhea}', doc #>> '{fields,child_danger_signs,child_diarrhea}'),'')::BOOLEAN AS child_severe_diarrhea,
    NULLIF(doc #>> '{fields,child_danger_signs,refer_child_danger_sign_flag}', '')::BOOLEAN AS refer_child_danger_sign_flag,
    NULLIF(COALESCE(doc #>> '{fields,child_other_danger_signs,child_drink_below_6_months}', doc #>> '{fields,child_danger_signs,child_drink_below_6_months}'),'')::BOOLEAN AS child_drink_below_6_months,
    NULLIF(COALESCE(doc #>> '{fields,child_other_danger_signs,child_drink_6_months_to_2_years}',doc #>> '{fields,child_danger_signs,child_drink_6_months_to_2_years}'),'')::BOOLEAN AS child_drink_6_months_to_2_years,
    NULLIF(COALESCE(doc #>> '{fields,child_other_danger_signs,child_drink_above_2_years}',doc #>> '{fields,child_danger_signs,child_drink_above_2_years}'),'')::BOOLEAN AS child_drink_above_2_years,
    NULLIF(COALESCE(doc #>> '{fields,child_other_danger_signs,child_coughing}',doc #>> '{fields,child_danger_signs,child_coughing}'),'')::BOOLEAN AS child_coughing,
    NULLIF(COALESCE(doc #>> '{fields,child_other_danger_signs,child_cold}',doc #>> '{fields,child_danger_signs,child_cold}'),'')::BOOLEAN AS child_cold,
    NULLIF(COALESCE(doc #>> '{fields,child_other_danger_signs,child_skin_boils}',doc #>> '{fields,child_danger_signs,child_skin_boils}'),'')::BOOLEAN AS child_skin_boils,
    NULLIF(doc #>> '{fields,child_other_danger_signs,child_mild_diarrhea }', '')::BOOLEAN AS child_mild_diarrhea,
    NULLIF(doc #>> '{fields,child_other_danger_signs,refer_child_other_danger_sign_flag}', '')::BOOLEAN AS refer_child_other_danger_sign_flag,
    doc #>> '{fields,malnutrition_anemia,growth_graph_range}' AS growth_graph_range,
    doc #>> '{fields,malnutrition_anemia,muac_color}' AS muac_color,
    NULLIF(doc #>> '{fields,malnutrition_anemia,refer_muac_flag}', '')::BOOLEAN AS refer_muac_flag,
    doc #>> '{fields,malnutrition_anemia,palm_pallor}' AS palm_pallor,
    NULLIF(doc #>> '{fields,malnutrition_anemia,refer_palm_pallor_flag}', '')::BOOLEAN AS refer_palm_pallor_flag,
    doc #>> '{fields,malnutrition_anemia,diff_foods_should_give_child}' AS diff_foods_should_give_child,
    NULLIF(doc #>> '{fields,malnutrition_anemia,score}', '')::INTEGER AS food_varieties,
    NULLIF(doc #>> '{fields,malnutrition_anemia,calculated_score}', '')::INTEGER AS food_variety_score,
    doc #>> '{fields,malnutrition_anemia,mny_solid_food_feed_child}' AS mny_solid_food_feed_child,
    NULLIF(doc #>> '{fields,small_baby_ever}', '')::BOOLEAN AS small_baby_ever,
    NULLIF(doc #>> '{fields,wash,subgroup_cleanliness,hand_wash_importance}','')::BOOLEAN  AS is_hand_wash_important,
    NULLIF(doc #>> '{fields,wash,subgroup_health_concerns,health_concerns}','') AS selected_health_concerns,
    NULLIF(COALESCE(doc #>> '{fields,essential_newborn_breastfeeding,currently_breastfeeding}', doc #>> '{fields,essential_newborn_breastfeeding,breastfeeding,currently_breastfeeding}',doc #>> '{fields,small_baby_breastfeeding,small_baby_currently_breastfeeding}'),'')::BOOLEAN AS currently_breastfeeding,
    NULLIF(COALESCE(doc #>> '{fields,essential_newborn_breastfeeding,exclusively_breastfeeding}',doc #>> '{fields,essential_newborn_breastfeeding,exclusive_breastfeeding}', doc #>> '{fields,essential_newborn_breastfeeding,breastfeeding,exclusively_breastfeeding}',doc #>> '{fields,small_baby_breastfeeding,small_baby_breastfeed_exclusively}'), '')::BOOLEAN AS exclusively_breastfeeding,
    NULLIF(doc #>> '{fields,essential_newborn_breastfeeding,exclusive_breastfeeding_multiple_choice}','') AS exclusive_breastfeeding_multiple_choice,
    NULLIF(doc #>> '{fields,essential_newborn_breastfeeding_positioning,is_breastfeeding_positioning_ok}', '')::BOOLEAN AS is_breastfeeding_positioning_ok,
    NULLIF(doc #>> '{fields,essential_newborn_breastfeeding_positioning,suckling_effectively}', '')::BOOLEAN AS suckling_effectively,
    NULLIF(COALESCE(doc #>> '{fields,small_baby_breastfeeding,small_baby_ever_breastfed}', doc #>> '{fields,essential_newborn_breastfeeding,ever_breastfed}',doc #>> '{fields,essential_newborn_breastfeeding,breastfeeding,ever_breastfed}'), '')::BOOLEAN AS ever_breastfed,
    NULLIF(COALESCE(doc #>> '{fields,small_baby_breastfeeding,small_baby_time_breastfeed}',doc #>> '{fields,essential_newborn_breastfeeding,time_to_breastfeed}',doc #>> '{fields,essential_newborn_breastfeeding,breastfeeding,time_to_breastfeed}'),'') AS time_to_breastfeed,
    NULLIF(COALESCE(doc #>> '{fields,small_baby_breastfeeding,small_baby_times_breastfed_daily}', doc #>> '{fields,essential_newborn_breastfeeding,baby_time_breastfed_daily}'),'') AS baby_times_breastfed_daily,
    NULLIF(COALESCE(doc #>> '{fields,essential_newborn_breastfeeding,baby_breastfeed_well}', doc #>> '{fields,small_baby_breastfeeding,small_baby_breastfeed_well}'), '')::BOOLEAN AS breastfeed_well,
    NULLIF(doc #>> '{fields,small_baby_breastfeeding,small_baby_other_than_breast_milk}', '')::BOOLEAN AS small_baby_other_than_breast_milk,
    NULLIF(doc #>> '{fields,essential_newborn_care_nutrition,still_breastfeeding}', '')::BOOLEAN AS still_breastfeeding,
    NULLIF(doc #>> '{fields,immunizations,has_health_card}', '')::BOOLEAN AS has_health_card,
    NULLIF(doc #>> '{fields,immunizations,record_vaccines,received_bcg}', '')::BOOLEAN AS received_bcg,
    TO_DATE(doc #>> '{fields,immunizations,record_vaccines,bcg_date}', 'YYYY-MM-DD') AS bcg_date,
    NULLIF(doc #>> '{fields,immunizations,record_vaccines,received_bopv0}', '')::BOOLEAN AS received_bopv0,
    TO_DATE(doc #>> '{fields,immunizations,record_vaccines,bopv0_date}', 'YYYY-MM-DD') AS bopv0_date,
    NULLIF(doc #>> '{fields,immunizations,record_vaccines,received_bopv1}', '')::BOOLEAN AS received_bopv1,
    TO_DATE(doc #>> '{fields,immunizations,record_vaccines,bopv1_date}', 'YYYY-MM-DD') AS bopv1_date,
    NULLIF(doc #>> '{fields,immunizations,record_vaccines,received_dtp_hepb_hib1}', '')::BOOLEAN AS received_dtp_hepb_hib1,
    TO_DATE(doc #>> '{fields,immunizations,record_vaccines,dtp_hebp_hib1_date}', 'YYYY-MM-DD') AS dtp_hepb_hib1_date,
    NULLIF(doc #>> '{fields,immunizations,record_vaccines,received_pcvi1}', '')::BOOLEAN AS received_pcvi1,
    TO_DATE(doc #>> '{fields,immunizations,record_vaccines,pcvi1_date}', 'YYYY-MM-DD') AS pcvi1_date,
    NULLIF(doc #>> '{fields,immunizations,record_vaccines,received_rota1}', '')::BOOLEAN AS received_rota1,
    TO_DATE(doc #>> '{fields,immunizations,record_vaccines,rota1_date}', 'YYYY-MM-DD') AS rota1_date,
    NULLIF(doc #>> '{fields,immunizations,record_vaccines,received_bopv2}', '')::BOOLEAN AS received_bopv2,
    TO_DATE(doc #>> '{fields,immunizations,record_vaccines,bopv2_date}', 'YYYY-MM-DD') AS bopv2_date,
    NULLIF(doc #>> '{fields,immunizations,record_vaccines,received_dtp_hepb_hib2}', '')::BOOLEAN AS received_dtp_hepb_hib2,
    TO_DATE(doc #>> '{fields,immunizations,record_vaccines,dtp_hebp_hib2_date}', 'YYYY-MM-DD') AS dtp_hepb_hib2_date,
    NULLIF(doc #>> '{fields,immunizations,record_vaccines,received_pcvi2}', '')::BOOLEAN AS received_pcvi2,
    TO_DATE(doc #>> '{fields,immunizations,record_vaccines,pcvi2_date}', 'YYYY-MM-DD') AS pcvi2_date,
    NULLIF(doc #>> '{fields,immunizations,record_vaccines,received_rota2}', '')::BOOLEAN AS received_rota2,
    TO_DATE(doc #>> '{fields,immunizations,record_vaccines,rota2_date}', 'YYYY-MM-DD') AS rota2_date,
    NULLIF(doc #>> '{fields,immunizations,record_vaccines,received_bopv3}', '')::BOOLEAN AS received_bopv3,
    TO_DATE(doc #>> '{fields,immunizations,record_vaccines,bopv3_date}', 'YYYY-MM-DD') AS bopv3_date,
    NULLIF(doc #>> '{fields,immunizations,record_vaccines,received_dtp_hepb_hib3}', '')::BOOLEAN AS received_dtp_hepb_hib3,
    TO_DATE(doc #>> '{fields,immunizations,record_vaccines,dtp_hebp_hib3_date}', 'YYYY-MM-DD') AS dtp_hepb_hib3_date,
    NULLIF(doc #>> '{fields,immunizations,record_vaccines,received_pcvi3}', '')::BOOLEAN AS received_pcvi3,
    TO_DATE(doc #>> '{fields,immunizations,record_vaccines,pcvi3_date}', 'YYYY-MM-DD') AS pcvi3_date,
    NULLIF(doc #>> '{fields,immunizations,record_vaccines,received_ipv}', '')::BOOLEAN AS received_ipv,
    TO_DATE(doc #>> '{fields,immunizations,record_vaccines,ipv_date}', 'YYYY-MM-DD') AS ipv_date,
    NULLIF(doc #>> '{fields,immunizations,record_vaccines,received_surua_rubella1}', '')::BOOLEAN AS received_surua_rubella1,
    TO_DATE(doc #>> '{fields,immunizations,record_vaccines,surua_rubella1_date}', 'YYYY-MM-DD') AS surua_rubella1_date,
    NULLIF(doc #>> '{fields,immunizations,record_vaccines,received_surua_rubella2}', '')::BOOLEAN AS received_surua_rubella2,
    TO_DATE(doc #>> '{fields,immunizations,record_vaccines,surua_rubella2_date}', 'YYYY-MM-DD') AS surua_rubella2_date,
    NULLIF(doc #>> '{fields,immunizations,vaccines_up_to_date}', '')::BOOLEAN AS vaccines_up_to_date,
    doc #>> '{fields,immunizations,why_not_vaccines_up_to_date}' AS why_not_vaccines_up_to_date,
    NULLIF(doc #>> '{fields,immunizations,refer_vaccines_flag}', '')::BOOLEAN AS refer_vaccines_flag,
    doc #>> '{fields,assess_dev_coach_play_communication,spend_time_with}' AS spend_time_with,
    NULLIF(doc #>> '{fields,assess_dev_coach_play_communication,child_age_months}', '')::INTEGER AS child_age_months,
    doc #>> '{fields,assess_dev_coach_play_communication,development_stage}' AS development_stage,
    doc #>> '{fields,assess_dev_coach_play_communication,play_communicate_lt_6mo,how_play}' AS how_play,
    doc #>> '{fields,assess_dev_coach_play_communication,play_communicate_lt_6mo,how_communicate}' AS how_communicate_lt_6mo,
    NULLIF(doc #>> '{fields,assess_dev_coach_play_communication,play_communicate_ge_6mo,how_play}', '')::BOOLEAN AS how_play_ge_6mo,
    doc #>> '{fields,assess_dev_coach_play_communication,play_communicate_ge_6mo,how_communicate}' AS how_communicate_ge_6mo,
    doc #>> '{fields,assess_behavior,how_interact}' AS how_interact,
    NULLIF(doc #>> '{fields,assess_behavior,has_observed_comforting}', '')::BOOLEAN AS has_observed_comforting,
    NULLIF(doc #>> '{fields,assess_behavior,has_observed_correcting}', '')::BOOLEAN AS has_observed_correcting,
    doc #>> '{fields,assess_behavior,how_correct}' AS how_correct,
    NULLIF(doc #>> '{fields,problem_solving,has_stress_concern_play_comm}', '')::BOOLEAN AS has_stress_concern_play_comm,
    NULLIF(doc #>> '{fields,problem_solving,has_time_concern_play_comm}', '')::BOOLEAN AS has_time_concern_play_comm,
    doc #>> '{fields,problem_solving,engage_with_child}' AS engage_with_child,
    doc #>> '{fields,problem_solving,who_engages}' AS who_engages,
    doc #>> '{fields,problem_solving,who_engages_other}' AS who_engages_other,
    NULLIF(doc #>> '{fields,problem_solving,who_engages_how_many_hours}', '')::INTEGER AS who_engages_how_many_hours,
    NULLIF(doc #>> '{fields,problem_solving,concern_toys}', '')::BOOLEAN AS concern_toys,
    NULLIF(doc #>> '{fields,problem_solving,plays_with_toys_homemade}', '')::BOOLEAN AS plays_with_toys_homemade,
    NULLIF(doc #>> '{fields,problem_solving,plays_with_toys_manufactured}', '')::BOOLEAN AS plays_with_toys_manufactured,
    NULLIF(doc #>> '{fields,problem_solving,plays_with_toys_household_objects}', '')::BOOLEAN AS plays_with_toys_household_objects,
    NULLIF(doc #>> '{fields,problem_solving,number_books}', '')::INTEGER AS number_books,
    NULLIF(doc #>> '{fields,problem_solving,concern_leave_child}', '')::BOOLEAN AS concern_leave_child,
    NULLIF(doc #>> '{fields,problem_solving,days_left_alone_more_than_1h}', '')::INTEGER AS days_left_alone_more_than_1h,
    NULLIF(doc #>> '{fields,problem_solving,days_in_care_of_other_child_more_than_1h}', '')::INTEGER AS days_in_care_of_other_child_more_than_1h,
    NULLIF(doc #>> '{fields,problem_solving,concern_harsh_treatment}', '')::BOOLEAN AS concern_harsh_treatment,
    NULLIF(doc #>> '{fields,problem_solving,concern_stressful_family_environment}', '')::BOOLEAN AS concern_stressful_family_environment,
    NULLIF(doc #>> '{fields,development_concerns,concern_slow_to_learn}', '')::BOOLEAN AS concern_slow_to_learn,
    NULLIF(doc #>> '{fields,development_concerns,slow_to_learn_delay_sitting}', '')::BOOLEAN AS slow_to_learn_delay_sitting,
    NULLIF(doc #>> '{fields,development_concerns,slow_to_learn_difficulty_seeing}', '')::BOOLEAN AS slow_to_learn_difficulty_seeing,
    NULLIF(doc #>> '{fields,development_concerns,slow_to_learn_difficulty_hearing}', '')::BOOLEAN AS slow_to_learn_difficulty_hearing,
    NULLIF(doc #>> '{fields,development_concerns,slow_to_learn_understand_speech}', '')::BOOLEAN AS slow_to_learn_understand_speech,
    NULLIF(doc #>> '{fields,development_concerns,slow_to_learn_difficulty_walking_moving}', '')::BOOLEAN AS slow_to_learn_difficulty_walking_moving,
    NULLIF(doc #>> '{fields,development_concerns,slow_to_learn_has_fits}', '')::BOOLEAN AS slow_to_learn_has_fits,
    NULLIF(doc #>> '{fields,development_concerns,slow_to_learn_compared_with_kids}', '')::BOOLEAN AS slow_to_learn_compared_with_kids,
    NULLIF(doc #>> '{fields,development_concerns,slow_to_learn_does_speak}', '')::BOOLEAN AS slow_to_learn_does_speak,
    NULLIF(doc #>> '{fields,development_concerns,slow_to_learn_speech_different}', '')::BOOLEAN AS slow_to_learn_speech_different,
    NULLIF(doc #>> '{fields,development_concerns,slow_to_learn_can_name_object}', '')::BOOLEAN AS slow_to_learn_can_name_object,
    NULLIF(doc #>> '{fields,development_concerns,slow_to_learn_appears_mentally_backward}', '')::BOOLEAN AS slow_to_learn_appears_mentally_backward,
    NULLIF(doc #>> '{fields,development_concerns,refer_slow_to_learn_specifics_flag}', '')::BOOLEAN AS refer_slow_to_learn_specifics_flag,
    NULLIF(doc #>> '{fields,male_involvement,was_male_present}', '')::BOOLEAN AS was_male_present,
    NULLIF(doc #>> '{fields,male_involvement,male_present_entire_visit}', '')::BOOLEAN AS male_present_entire_visit,
    doc #>> '{fields,male_involvement,partner_interaction}' AS partner_interaction,
    NULLIF(doc #>> '{fields,child_stool_disposal,has_latrine}', '')::BOOLEAN AS has_latrine,
    doc #>> '{fields,child_stool_disposal,latrine_type}' AS latrine_type,
    NULLIF(doc #>> '{fields,llints,has_mosquito_net}', '')::BOOLEAN AS has_mosquito_net,
    NULLIF(doc #>> '{fields,group_summary,any_referral}', '')::BOOLEAN AS any_referral,
    NULLIF(doc #>> '{geolocation,latitude}', '')::DECIMAL AS latitude,
    NULLIF(doc #>> '{geolocation,longitude}', '')::DECIMAL AS longitude,
    NULLIF(doc #>> '{geolocation,altitude}', '')::DECIMAL AS altitude,
    NULLIF(doc #>> '{geolocation,accuracy}', '')::DECIMAL AS accuracy 
  FROM 
	  couchdb	
  WHERE 
	  doc ->> 'form' = 'infant_child'
);
CREATE UNIQUE INDEX IF NOT EXISTS infant_child_reported_date_created_by_uuid ON useview_infant_child USING btree (reported_date, chv_uuid, patient_id);
-- Permissions
REASSIGN OWNED BY current_user TO full_access;
GRANT SELECT ON useview_infant_child TO full_access, dtree, periscope;
