name: CI

on:
  push:
    branches:
      - master
      - v*maintenance*
  pull_request:
    branches:
      - master
      - v*maintenance*

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    defaults:
      run:
        working-directory: .

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: sudo python -m pip install git+https://github.com/medic/pyxform.git@medic-conf-1.17#egg=pyxform-medic
      #- run: sudo python -m pip install sqlfluff
      - run: npm ci
      - run: npm test
