DROP MATERIALIZED VIEW IF EXISTS moh_agg_child_referrals;
CREATE MATERIALIZED VIEW moh_agg_child_referrals AS (
  SELECT
    district,
    shehia,
    issued_month,
    sum(followup_within3days_neonatal_danger_sign_flag) AS followup_within3days_neonatal_danger_sign_flag,
    sum(followup_within3days_secondary_neonatal_danger_sign) AS followup_within3days_secondary_neonatal_danger_sign,
    sum(followup_within3days_child_danger_sign) AS followup_within3days_child_danger_sign,
    sum(followup_within3days_child_other_danger_sign) AS followup_within3days_child_other_danger_sign,
    sum(followup_within7days_child_danger_sign) AS followup_within7days_child_danger_sign,
    sum(followup_within7days_neonatal_danger_sign_flag) AS followup_within7days_neonatal_danger_sign_flag,
    sum(followup_within7days_secondary_neonatal_danger_sign) AS followup_within7days_secondary_neonatal_danger_sign,
    sum(followup_within7days_child_other_danger_sign) AS followup_within7days_child_other_danger_sign,
    sum(followup_within7days_slow_to_learn_specifics) AS followup_within7days_slow_to_learn_specifics,
    sum(slow_to_learn_specifics_cancelled_followup) AS slow_to_learn_specifics_cancelled_followup,
    sum(neonatal_danger_sign_cancelled_followup) AS neonatal_danger_sign_cancelled_followup,
    sum(vaccines_cancelled_followup) AS vaccines_cancelled_followup,
    sum(secondary_neonatal_danger_sign_cancelled_followup) AS secondary_neonatal_danger_sign_cancelled_followup,
    sum(followup_within7days_muac) AS followup_within7days_muac,
    sum(muac_cancelled_followup) AS muac_cancelled_followup,
    sum(followup_within7days_palm_pallor) AS followup_within7days_palm_pallor,
    sum(palm_pallor_cancelled_followup) AS palm_pallor_cancelled_followup,
    sum(followup_within7days_child_other_danger_sign) AS followup_within7days_child_other_danger_sign,
    sum(child_other_danger_sign_cancelled_followup) AS child_other_danger_sign_cancelled_followup,
    sum(followup_within7days_small_baby) AS followup_within7days_small_baby,
    sum(small_baby_cancelled_followup) AS small_baby_cancelled_followup,
    sum(issued_referrals_muac) AS issued_referrals_muac,
    sum(followup_within3days_muac) AS followup_within3days_muac,
    sum(issued_referrals_palm_pallor) AS issued_referrals_palm_pallor,
    sum(followup_within3days_palm_pallor) AS followup_within3days_palm_pallor,
    sum(issued_referrals_child_other_danger_sign) AS issued_referrals_child_other_danger_sign,
    sum(child_other_danger_sign_got_services) AS child_other_danger_sign_got_services,
    sum(child_danger_sign_got_services) AS child_danger_sign_got_services,
    sum(child_danger_sign_cancelled_followup) AS child_danger_sign_cancelled_followup,
    sum(child_danger_sign_went_to_facility) - sum(child_danger_sign_got_services) AS child_danger_signs_facility_no_services,
    sum(child_danger_sign_went_to_facility) AS child_danger_sign_went_to_facility,
    sum(child_danger_sign_didnt_go_facility) AS child_danger_sign_didnt_go_facility,
    sum(slow_to_learn_specifics_went_to_facility) AS slow_to_learn_specifics_went_to_facility,
    sum((slow_to_learn_specifics_went_to_facility = 0)::INT) AS slow_to_learn_specifics_didnt_go_facility,
    sum(slow_to_learn_specifics_got_services) AS slow_to_learn_specifics_got_services,
    sum((neonatal_danger_sign_went_to_facility = 0)::INT) AS neonatal_danger_sign_didnt_go_facility,
    sum(neonatal_danger_sign_got_services) AS neonatal_danger_sign_got_services,
    sum(secondary_neonatal_danger_sign_went_to_facility) AS secondary_neonatal_danger_sign_went_to_facility,
    sum((secondary_neonatal_danger_sign_went_to_facility = 0)::INT) AS secondary_neonatal_danger_sign_didnt_go_facility,
    sum(secondary_neonatal_danger_sign_got_services) AS secondary_neonatal_danger_sign_got_services,
    sum(muac_went_to_facility) AS muac_went_to_facility,
    sum((muac_went_to_facility = 0)::INT) AS muac_didnt_go_facility,
    sum(muac_got_services) AS muac_got_services,
    sum((palm_pallor_went_to_facility = 0)::INT) AS palm_pallor_didnt_go_facility,
    sum(palm_pallor_went_to_facility) AS palm_pallor_went_to_facility,
    sum(palm_pallor_got_services) AS palm_pallor_got_services,
    sum(child_other_danger_sign_went_to_facility) AS child_other_danger_sign_went_to_facility,
    sum((child_other_danger_sign_went_to_facility = 0)::INT) AS child_other_danger_sign_didnt_go_facility,
    sum(child_other_danger_sign_got_services) AS child_other_danger_sign_got_services,
    sum(small_baby_went_to_facility) AS small_baby_went_to_facility,
    sum((small_baby_went_to_facility = 0)::INT) AS small_baby_didnt_go_facility,
    sum(small_baby_got_services) AS small_baby_got_services,
    'sex' AS disaggregation,
    substring(disaggregation_value, '((female|male)|\d+_\d+(?=years)|default)') AS disaggregation_value
  FROM agg_child_referrals
  GROUP BY district, shehia, issued_month, disaggregation, substring(disaggregation_value, '((female|male)|\d+_\d+(?=years)|default)')
);
CREATE UNIQUE INDEX IF NOT EXISTS moh_district_month_shehia_moh_agg_child_referrals ON moh_agg_child_referrals USING btree (district, shehia, issued_month, disaggregation, disaggregation_value);
ALTER MATERIALIZED VIEW moh_agg_child_referrals OWNER TO full_access;
GRANT SELECT ON moh_agg_child_referrals TO dtree;